// --- Datos (sin cambios) ---
    const modelosTipo = ["San Andreas", "Minecraft", "MinecraftMobs", "Minecraft Aldeanos", "Otros"];
        //const arraySex = ["Masculino", "Femenino", "N/A"];
    const modelos = [
        {nombre:"CJ", tipo:"San Andreas", categoria:"Especial", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Sweet", tipo:"San Andreas", categoria:"Especial", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Ryder", tipo:"San Andreas", categoria:"Especial", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Smoke", tipo:"San Andreas", categoria:"Especial", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Ballas1", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Ballas2", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Ballas3", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"bfori", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"bfyri", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"bmobar", tipo:"San Andreas", categoria:"Oficio, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"bmochil", tipo:"San Andreas", categoria:"Oficio, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"bmycr", tipo:"San Andreas", categoria:"Peaton, Oficio, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"bmydj", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"cwmyhb1", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"dnfolc2", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"Fam1", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Fam2", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Fam3", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"gangrl3", tipo:"San Andreas", categoria:"Especial", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"lapd1", tipo:"San Andreas", categoria:"Oficio, Policia, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"lsv1", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"lsv2", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"lsv3", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"maccer", tipo:"San Andreas", categoria:"Especial", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"male01", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"ogloc", tipo:"San Andreas", categoria:"Especial", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"sfr1", tipo:"San Andreas", categoria:"Pandilla", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"sfr2", tipo:"San Andreas", categoria:"Pandilla", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"sfr3", tipo:"San Andreas", categoria:"Pandilla", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Smokev", tipo:"San Andreas", categoria:"Especial", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"sofost", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"somyri", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"swfost", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"swmotr4", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"swmotr5", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"vla1", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"vla2", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"vla3", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"wfypro", tipo:"San Andreas", categoria:"Oficio, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"wmyst", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"wmyst v2", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"woozie", tipo:"San Andreas", categoria:"Especial", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"dsher", tipo:"San Andreas", categoria:"Policia, Oficio, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"army", tipo:"San Andreas", categoria:"Policia, Oficio, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"fbi", tipo:"San Andreas", categoria:"Policia, Oficio, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"swat", tipo:"San Andreas", categoria:"Policia, Oficio, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"lapdm1", tipo:"San Andreas", categoria:"Policia, Oficio, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"csher", tipo:"San Andreas", categoria:"Policia, Oficio, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"lvpd1", tipo:"San Andreas", categoria:"Policia, Oficio, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"sfpd1", tipo:"San Andreas", categoria:"Policia, Oficio, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"lvpdm1", tipo:"San Andreas", categoria:"Policia, Oficio", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"sfpdm1", tipo:"San Andreas", categoria:"Policia, Oficio", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"hernandez", tipo:"San Andreas", categoria:"Policia, Oficio, Especial", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"pulaski", tipo:"San Andreas", categoria:"Policia, Oficio, Especial", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"tenpenny", tipo:"San Andreas", categoria:"Policia, Oficio, Especial", sexo:"Masculino", rig:"ARPFortnite"},

        {nombre:"Cientifico 1", tipo:"San Andreas", categoria:"Oficio, Especial, Mod", sexo:"Masculino", rig:"ARPFortnite"},

        {nombre:"Zombie 1", tipo:"San Andreas", categoria:"Mod, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Zombie 2", tipo:"San Andreas", categoria:"Mod, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Zombie 3", tipo:"San Andreas", categoria:"Mod, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Zombie 4", tipo:"San Andreas", categoria:"Mod, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Zombie 5", tipo:"San Andreas", categoria:"Mod, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Zombie 6", tipo:"San Andreas", categoria:"Mod, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Zombie 7", tipo:"San Andreas", categoria:"Mod, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Zombie 8", tipo:"San Andreas", categoria:"Mod, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Zombie 9", tipo:"San Andreas", categoria:"Mod, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Zombie 10", tipo:"San Andreas", categoria:"Mod, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Zombie 11", tipo:"San Andreas", categoria:"Mod, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Zombie 12", tipo:"San Andreas", categoria:"Mod, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Zombie 13", tipo:"San Andreas", categoria:"Mod, Zombie", sexo:"Masculino", rig:"ARPFortnite"},

        {nombre:"Policia 1", tipo:"San Andreas", categoria:"Mod, Policia, Oficio", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Policia 2", tipo:"San Andreas", categoria:"Mod, Policia, Oficio", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Policia 3", tipo:"San Andreas", categoria:"Mod, Policia, Oficio", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Policia 4", tipo:"San Andreas", categoria:"Mod, Policia, Oficio", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Policia 5", tipo:"San Andreas", categoria:"Mod, Policia, Oficio", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Policia 6", tipo:"San Andreas", categoria:"Mod, Policia, Oficio", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Policia 7", tipo:"San Andreas", categoria:"Mod, Policia, Oficio", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Policia 8", tipo:"San Andreas", categoria:"Mod, Policia, Oficio", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Policia 9", tipo:"San Andreas", categoria:"Mod, Policia, Oficio", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Policia 10", tipo:"San Andreas", categoria:"Mod, Policia, Oficio", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Policia 11", tipo:"San Andreas", categoria:"Mod, Policia, Oficio", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Policia 12", tipo:"San Andreas", categoria:"Mod, Policia, Oficio", sexo:"Masculino", rig:"ARPFortnite"},

        {nombre:"Director del juego", tipo:"San Andreas", categoria:"Mod", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Soldado circulo", tipo:"San Andreas", categoria:"Mod", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Soldado cuadrado", tipo:"San Andreas", categoria:"Mod", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Soldado triangulo", tipo:"San Andreas", categoria:"Mod", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Papanoel", tipo:"San Andreas", categoria:"Mod", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Hitler", tipo:"San Andreas", categoria:"Mod", sexo:"Masculino", rig:"ARPFortnite"},
        
        

        {nombre:"MC Skeleton", tipo:"MinecraftMobs", categoria:"", sexo:"Masculino", rig:"MCMob"},
        {nombre:"MC WitherSkeleton", tipo:"MinecraftMobs", categoria:"", sexo:"Masculino", rig:"MCMob"},
        {nombre:"MC Zombie", tipo:"MinecraftMobs", categoria:"", sexo:"Masculino", rig:"MCMob"},

        {nombre:"MC Araujo Barcelona", tipo:"Minecraft", categoria:"MC Futbolista, MC Barcelona", sexo:"Masculino", rig:"MCprep"},
        {nombre:"MC Balla Barcelona", tipo:"Minecraft", categoria:"MC Futbolista, MC San Andreas", sexo:"Masculino", rig:"MCprep"},
        {nombre:"MC Creeeper Barcelona", tipo:"Minecraft", categoria:"MC Futbolista, MC Mob", sexo:"Masculino", rig:"MCprep"},
        {nombre:"MC Esqueleto Barcelona", tipo:"Minecraft", categoria:"MC Futbolista, MC Mob", sexo:"Masculino", rig:"MCprep"},
        {nombre:"MC Iniesta Barcelona", tipo:"Minecraft", categoria:"MC Futbolista, MC Barcelona", sexo:"Masculino", rig:"MCprep"},
        {nombre:"MC Lamine Barcelona", tipo:"Minecraft", categoria:"MC Futbolista, MC Barcelona", sexo:"Masculino", rig:"MCprep"},
        {nombre:"MC Mbappe Barcelona", tipo:"Minecraft", categoria:"MC Futbolista, MC Real Madrid", sexo:"Masculino", rig:"MCprep"},
        {nombre:"MC Neymar Barcelona", tipo:"Minecraft", categoria:"MC Futbolista, MC Barcelona", sexo:"Masculino", rig:"MCprep"},
        {nombre:"MC Pele Barcelona", tipo:"Minecraft", categoria:"MC Futbolista", sexo:"Masculino", rig:"MCprep"},
        {nombre:"MC Player Barcelona", tipo:"Minecraft", categoria:"MC Futbolista, MC Player", sexo:"Masculino", rig:"MCprep"},
        {nombre:"MC Ronaldhino Barcelona", tipo:"Minecraft", categoria:"MC Futbolista, MC Barcelona", sexo:"Masculino", rig:"MCprep"},
        {nombre:"MC Xavi Barcelona", tipo:"Minecraft", categoria:"MC Futbolista, MC Barcelona", sexo:"Masculino", rig:"MCprep"},
        {nombre:"MC Messi Barcelona", tipo:"Minecraft", categoria:"MC Futbolista, MC Barcelona", sexo:"Masculino", rig:"MCprep"},

        {nombre:"MC Bellingham Real Madrid", tipo:"Minecraft", categoria:"MC Futbolista, MC Real Madrid", sexo:"Masculino", rig:"MCprep"},
        {nombre:"MC Cr7 Real Madrid", tipo:"Minecraft", categoria:"MC Futbolista, MC Real Madrid", sexo:"Masculino", rig:"MCprep"},
        {nombre:"MC Endrick Real Madrid", tipo:"Minecraft", categoria:"MC Futbolista, MC Real Madrid", sexo:"Masculino", rig:"MCprep"},
        {nombre:"MC Kaka Real Madrid", tipo:"Minecraft", categoria:"MC Futbolista, MC Real Madrid", sexo:"Masculino", rig:"MCprep"},
        {nombre:"MC Kroos Real Madrid", tipo:"Minecraft", categoria:"MC Futbolista, MC Real Madrid", sexo:"Masculino", rig:"MCprep"},
        {nombre:"MC Mbappe Real Madrid", tipo:"Minecraft", categoria:"MC Futbolista, MC Real Madrid", sexo:"Masculino", rig:"MCprep"},
        {nombre:"MC Modric Real Madrid", tipo:"Minecraft", categoria:"MC Futbolista, MC Real Madrid", sexo:"Masculino", rig:"MCprep"},
        {nombre:"MC Rodrigo Real Madrid", tipo:"Minecraft", categoria:"MC Futbolista, MC Real Madrid", sexo:"Masculino", rig:"MCprep"},
        {nombre:"MC Rudiger Real Madrid", tipo:"Minecraft", categoria:"MC Futbolista, MC Real Madrid", sexo:"Masculino", rig:"MCprep"},
        {nombre:"MC Vinicius Real Madrid", tipo:"Minecraft", categoria:"MC Futbolista, MC Real Madrid", sexo:"Masculino", rig:"MCprep"},

        {nombre:"MC David Silva Manchester City", tipo:"Minecraft", categoria:"MC Futbolista, MC Manchester City", sexo:"Masculino", rig:"MCprep"},
        {nombre:"MC Sergio Aguero Manchester City", tipo:"Minecraft", categoria:"MC Futbolista, MC Manchester City", sexo:"Masculino", rig:"MCprep"},
        {nombre:"MC Player 3 Manchester City", tipo:"Minecraft", categoria:"MC Futbolista, MC Manchester City, MC Player", sexo:"Masculino", rig:"MCprep"},
        {nombre:"MC Player 2 Manchester City", tipo:"Minecraft", categoria:"MC Futbolista, MC Manchester City, MC Player", sexo:"Masculino", rig:"MCprep"},
        {nombre:"MC Player 1 Manchester City", tipo:"Minecraft", categoria:"MC Futbolista, MC Manchester City, MC Player", sexo:"Masculino", rig:"MCprep"},
        {nombre:"MC Julian Alvarez Manchester City", tipo:"Minecraft", categoria:"MC Futbolista, MC Manchester City", sexo:"Masculino", rig:"MCprep"},
        {nombre:"MC Jason Manchester City", tipo:"Minecraft", categoria:"MC Futbolista, MC Manchester City", sexo:"Masculino", rig:"MCprep"},
        {nombre:"MC Halland Manchester City", tipo:"Minecraft", categoria:"MC Futbolista, MC Manchester City", sexo:"Masculino", rig:"MCprep"},
        {nombre:"MC Gundogan Manchester City", tipo:"Minecraft", categoria:"MC Futbolista, MC Manchester City", sexo:"Masculino", rig:"MCprep"},
        {nombre:"MC Foden Manchester City", tipo:"Minecraft", categoria:"MC Futbolista, MC Manchester City", sexo:"Masculino", rig:"MCprep"},
        {nombre:"MC Balotelli Manchester City", tipo:"Minecraft", categoria:"MC Futbolista, MC Manchester City", sexo:"Masculino", rig:"MCprep"},

        {nombre:"Desierto Albañil", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Albañil, Desierto", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Desierto Bibliotecario", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Bibliotecario, Desierto", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Desierto Carnicero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Carnicero, Desierto", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Desierto Cartografo", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Cartografo, Desierto", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Desierto Clerigo", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Clerigo, Desierto", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Desierto Desempleado", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Desempleado, Desierto", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Desierto Flechero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Flechero, Desierto", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Desierto Granjero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Granjero, Desierto", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Desierto Herrero de armaduras", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Herrero de armaduras, Desierto", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Desierto Herrero de armas", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Herrero de armas, Desierto", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Desierto Herrero de herramientas", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Herrero de herramientas, Desierto", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Desierto Pastor", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Pastor, Desierto", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Desierto Peletero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Peletero, Desierto", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Desierto Pescador", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Pescador, Desierto", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Desierto Simplon", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Simplon, Desierto", sexo:"Masculino", rig:"Aldeano"},

        {nombre:"Desnudo Albañil", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Albañil, Desnudo", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Desnudo Bibliotecario", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Bibliotecario, Desnudo", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Desnudo Carnicero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Carnicero, Desnudo", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Desnudo Cartografo", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Cartografo, Desnudo", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Desnudo Clerigo", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Clerigo, Desnudo", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Desnudo Desempleado", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Desempleado, Desnudo", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Desnudo Flechero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Flechero, Desnudo", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Desnudo Granjero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Granjero, Desnudo", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Desnudo Herrero de armaduras", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Herrero de armaduras, Desnudo", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Desnudo Herrero de armas", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Herrero de armas, Desnudo", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Desnudo Herrero de herramientas", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Herrero de herramientas, Desnudo", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Desnudo Pastor", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Pastor, Desnudo", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Desnudo Peletero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Peletero, Desnudo", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Desnudo Pescador", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Pescador, Desnudo", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Desnudo Simplon", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Simplon, Desnudo", sexo:"Masculino", rig:"Aldeano"},

        {nombre:"Jungla Albañil", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Albañil, Jungla", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Jungla Bibliotecario", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Bibliotecario, Jungla", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Jungla Carnicero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Carnicero, Jungla", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Jungla Cartografo", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Cartografo, Jungla", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Jungla Clerigo", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Clerigo, Jungla", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Jungla Desempleado", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Desempleado, Jungla", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Jungla Flechero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Flechero, Jungla", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Jungla Granjero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Granjero, Jungla", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Jungla Herrero de armaduras", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Herrero de armaduras, Jungla", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Jungla Herrero de armas", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Herrero de armas, Jungla", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Jungla Herrero de herramientas", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Herrero de herramientas, Jungla", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Jungla Pastor", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Pastor, Jungla", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Jungla Peletero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Peletero, Jungla", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Jungla Pescador", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Pescador, Jungla", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Jungla Simplon", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Simplon, Jungla", sexo:"Masculino", rig:"Aldeano"},

        {nombre:"Llanura Albañil", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Albañil, Llanura", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Llanura Bibliotecario", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Bibliotecario, Llanura", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Llanura Carnicero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Carnicero, Llanura", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Llanura Cartografo", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Cartografo, Llanura", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Llanura Clerigo", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Clerigo, Llanura", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Llanura Desempleado", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Desempleado, Llanura", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Llanura Flechero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Flechero, Llanura", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Llanura Granjero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Granjero, Llanura", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Llanura Herrero de armaduras", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Herrero de armaduras, Llanura", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Llanura Herrero de armas", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Herrero de armas, Llanura", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Llanura Herrero de herramientas", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Herrero de herramientas, Llanura", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Llanura Pastor", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Pastor, Llanura", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Llanura Peletero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Peletero, Llanura", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Llanura Pescador", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Pescador, Llanura", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Llanura Simplon", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Simplon, Llanura", sexo:"Masculino", rig:"Aldeano"},

        {nombre:"Nieve Albañil", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Albañil, Nieve", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Nieve Bibliotecario", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Bibliotecario, Nieve", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Nieve Carnicero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Carnicero, Nieve", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Nieve Cartografo", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Cartografo, Nieve", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Nieve Clerigo", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Clerigo, Nieve", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Nieve Desempleado", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Desempleado, Nieve", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Nieve Flechero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Flechero, Nieve", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Nieve Granjero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Granjero, Nieve", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Nieve Herrero de armaduras", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Herrero de armaduras, Nieve", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Nieve Herrero de armas", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Herrero de armas, Nieve", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Nieve Herrero de herramientas", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Herrero de herramientas, Nieve", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Nieve Pastor", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Pastor, Nieve", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Nieve Peletero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Peletero, Nieve", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Nieve Pescador", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Pescador, Nieve", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Nieve Simplon", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Simplon, Nieve", sexo:"Masculino", rig:"Aldeano"},

        {nombre:"Pantano Albañil", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Albañil, Pantano", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Pantano Bibliotecario", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Bibliotecario, Pantano", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Pantano Carnicero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Carnicero, Pantano", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Pantano Cartografo", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Cartografo, Pantano", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Pantano Clerigo", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Clerigo, Pantano", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Pantano Desempleado", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Desempleado, Pantano", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Pantano Flechero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Flechero, Pantano", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Pantano Granjero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Granjero, Pantano", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Pantano Herrero de armaduras", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Herrero de armaduras, Pantano", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Pantano Herrero de armas", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Herrero de armas, Pantano", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Pantano Herrero de herramientas", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Herrero de herramientas, Pantano", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Pantano Pastor", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Pastor, Pantano", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Pantano Peletero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Peletero, Pantano", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Pantano Pescador", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Pescador, Pantano", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Pantano Simplon", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Simplon, Pantano", sexo:"Masculino", rig:"Aldeano"},

        {nombre:"Sabana Albañil", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Albañil, Sabana", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Sabana Bibliotecario", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Bibliotecario, Sabana", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Sabana Carnicero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Carnicero, Sabana", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Sabana Cartografo", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Cartografo, Sabana", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Sabana Clerigo", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Clerigo, Sabana", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Sabana Desempleado", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Desempleado, Sabana", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Sabana Flechero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Flechero, Sabana", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Sabana Granjero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Granjero, Sabana", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Sabana Herrero de armaduras", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Herrero de armaduras, Sabana", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Sabana Herrero de armas", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Herrero de armas, Sabana", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Sabana Herrero de herramientas", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Herrero de herramientas, Sabana", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Sabana Pastor", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Pastor, Sabana", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Sabana Peletero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Peletero, Sabana", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Sabana Pescador", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Pescador, Sabana", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Sabana Simplon", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Simplon, Sabana", sexo:"Masculino", rig:"Aldeano"},

        {nombre:"Taiga Albañil", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Albañil, Taiga", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Taiga Bibliotecario", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Bibliotecario, Taiga", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Taiga Carnicero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Carnicero, Taiga", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Taiga Cartografo", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Cartografo, Taiga", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Taiga Clerigo", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Clerigo, Taiga", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Taiga Desempleado", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Desempleado, Taiga", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Taiga Flechero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Flechero, Taiga", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Taiga Granjero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Granjero, Taiga", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Taiga Herrero de armaduras", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Herrero de armaduras, Taiga", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Taiga Herrero de armas", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Herrero de armas, Taiga", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Taiga Herrero de herramientas", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Herrero de herramientas, Taiga", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Taiga Pastor", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Pastor, Taiga", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Taiga Peletero", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Peletero, Taiga", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Taiga Pescador", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Pescador, Taiga", sexo:"Masculino", rig:"Aldeano"},
        {nombre:"Taiga Simplon", tipo:"Minecraft Aldeanos", categoria:"Aldeanos, Simplon, Taiga", sexo:"Masculino", rig:"Aldeano"},
    ];
        /*for (let i = 1; i <= 50; i++) {
            let tipo, sexoDeterminado, categoriaEjemplo;
            const tipoIndex = i % modelosTipo.length;
            tipo = modelosTipo[tipoIndex];
            if (i % 3 === 0) sexoDeterminado = "N/A";
            else if (i % 2 === 0) sexoDeterminado = "Masculino";
            else sexoDeterminado = "Femenino";
            const catsBase = ["Aventura", "Acción", "Estrategia", "Puzzle", "Deporte", "Construcción", "Misterio", "Principal", "Secundario", "Jugador"];
            if (i % 4 === 0) categoriaEjemplo = `${catsBase[i%catsBase.length]}, ${catsBase[(i+1)%catsBase.length]}`;
            else if (i % 4 === 1) categoriaEjemplo = catsBase[i%catsBase.length];
            else if (i % 4 === 2) categoriaEjemplo = `${catsBase[i%catsBase.length]}, ${catsBase[(i+2)%catsBase.length]}, ${catsBase[(i+3)%catsBase.length]}`;
            else categoriaEjemplo = "General";
            modelos.push({ nombre: `Personaje${i}`, tipo: tipo, categoria: categoriaEjemplo, sexo: sexoDeterminado, rig: `RigDemo${i % 3}` });
        }*/
