    // Array para el primer grupo de checkboxes
    let arrayPropiedad = [
      {
        nombre: "Dead Island",
        data: [
          { id: "HeoL+w9/3", valor: "Base Context Head ChopPull ToD Med1HChL Minecraft mob" },
          { id: "VlM03WGAv", valor: "Base Context Head ChopPull ToD Med1HChR Minecraft mob" },
          { id: "qNqxwYYcU", valor: "Base Context Head ChopPull ToD Minecraft mob" },
          { id: "lDOEivoDy", valor: "Base Context Head ChopPull ToR Minecraft mob" },
          { id: "Swq96iy8l", valor: "Base Context Head HugeHit ToD Long2H Swe R erM Minecraft mob" },
          { id: "ws1iTPoWa", valor: "Base Context Head HugeHit ToD Minecraft mob" },
          { id: "CiZb7CXvK", valor: "Base Context Head HugeHit ToD Slicing L Minecraft mob" },
          { id: "4Kw*Up,*G", valor: "Base Context Head HugeHit ToD Slicing R Minecraft mob" },
          { id: "L5CNvxHEG", valor: "Base Context Head HugeHit ToD Weighty2HSwe L e Minecraft mob" },
          { id: "2GI+n9llN", valor: "Base Context Head HugeHit ToD Weighty2HSwe R e Minecraft mob" },
          { id: "OT*N5d;yK", valor: "Base Context Head StabThrow ToDL Minecraft mob" },
          { id: "Rn75/oi-A", valor: "Base Context Head StabThrow ToDR Minecraft mob" },
          { id: "-*K9zMKap", valor: "Base Context Stomach ChopPull ToL 1HM Ar Minecraft mob" },
          { id: "EW-Rr1x64", valor: "Base Context Stomach ChopPull ToL Minecraft mob" },
          { id: "8SvaqaPaA", valor: "Base Context Stomach ChopPull ToR Minecraft mob" },
          { id: "x350k*i+T", valor: "Base Context Stomach ChopPull ToUR Minecraft mob" },
          { id: ":Mj7BP_5f", valor: "Base Context Stomach HugeHit ToL Minecraft mob" },
          { id: "yBhEywzmc", valor: "Base Context Stomach HugeHit ToL Rake Ar Minecraft mob" },
          { id: "x*fR3AH_X", valor: "Base Context Stomach HugeHit ToR Minecraft mob" },
          { id: "JCX6BD:vE", valor: "Base Context Stomach HugeHit ToR Rake Ar Minecraft mob" },
          { id: "Mp,f:hBN2", valor: "Base Context Stomach HugeHit ToU L Minecraft mob" },
          { id: "AQDt5o_Y1", valor: "Base Context Stomach HugeHit ToU R Minecraft mob" },
          { id: "1x;o8kqr_", valor: "Base Context Stomach HugeStabSlash ToL A Minecraft mob" },
          { id: "BCXKRC,.e", valor: "Base Context Stomach StabThrow ToL Minecraft mob" },
          { id: "JUH7ZsXlP", valor: "Base Context Stomach StabThrow ToR Minecraft mob" },
          { id: "m1v4L/p/F", valor: "Paired Base Context Stomach StabSlash ToU S1H Minecraft mob" },
          { id: "-oAU5AQl+", valor: "Base Hit Recovery Hunched Abajo 02 Minecraft mob" },
          { id: "5cGX2T//a", valor: "Base Hit Recovery Hunched Abajo Minecraft mob" },
          { id: "+XJAa8ol9", valor: "Base Hit Recovery Hunched Adelante 02 Minecraft mob" },
          { id: "ZVYpwD-:x", valor: "Base Hit Recovery Hunched Adelante Minecraft mob" },
          { id: "yMbOMMnJc", valor: "Base Hit Recovery Hunched Arriba 02 Minecraft mob" },
          { id: "j5o1e7Fb2", valor: "Base Hit Recovery Hunched Arriba Minecraft mob" },
          { id: "ykmmsoVXq", valor: "Base Hit Recovery Hunched Atras 02 Minecraft mob" },
          { id: "R,fu+yGiz", valor: "Base Hit Recovery Hunched Atras Minecraft mob" },
          { id: "nZjrHBf/T", valor: "Base Hit Recovery Hunched Derecha 02 Minecraft mob" },
          { id: "Cnh.ucAGo", valor: "Base Hit Recovery Hunched Derecha Minecraft mob" },
          { id: "x/Sf**HFo", valor: "Base Hit Recovery Hunched Izquierda 02 Minecraft mob" },
          { id: "D;ior,h.t", valor: "Base Hit Recovery Hunched Izquierda Minecraft mob" },
          { id: "Aw+zOKb2Y", valor: "Base Hit Recovery OnFeet Abajo 02 Minecraft mob" },
          { id: "Wp,LDGlS;", valor: "Base Hit Recovery OnFeet Abajo Minecraft mob" },
          { id: "UbNlM:nV_", valor: "Base Hit Recovery OnFeet Adelante 02 Minecraft mob" },
          { id: "*3inZH0kg", valor: "Base Hit Recovery OnFeet Adelante Minecraft mob" },
          { id: ",xToA+BkQ", valor: "Base Hit Recovery OnFeet Atras 02 Minecraft mob" },
          { id: "_1-GpoQGy", valor: "Base Hit Recovery OnFeet Atras Minecraft mob" },
          { id: "hByF::c0t", valor: "Base Hit Recovery OnFeet Derecha 02 Minecraft mob" },
          { id: "RgXwpq,1p", valor: "Base Hit Recovery OnFeet Derecha Minecraft mob" },
          { id: "Vmsm8hqn1", valor: "Base Hit Recovery OnFeet Izquierda 02 Minecraft mob" },
          { id: "nQAS+cO-q", valor: "Base Hit Recovery OnFeet Izquierda Minecraft mob" },
          { id: "rVZm9,QjM", valor: "Base Hit Recovery OnFeet Legs Atras Minecraft mob" },
          { id: "p_cPxBiCc", valor: "Base Hit Recovery OnKnees Abajo 02 Minecraft mob" },
          { id: "Ddn96KDBu", valor: "Base Hit Recovery OnKnees Abajo Minecraft mob" },
          { id: "ATfSaFaYB", valor: "Base Hit Recovery OnKnees Adelante 02 Minecraft mob" },
          { id: "Mew5Gr3U+", valor: "Base Hit Recovery OnKnees Adelante Minecraft mob" },
          { id: "c0aNgTNbI", valor: "Base Hit Recovery OnKnees Atras 02 Minecraft mob" },
          { id: "f3uZ_psQm", valor: "Base Hit Recovery OnKnees Atras Minecraft mob" },
          { id: "KcW-/d.H1", valor: "Base Hit Recovery OnKnees Derecha 02 Minecraft mob" },
          { id: "qNzK6fRdK", valor: "Base Hit Recovery OnKnees Derecha Minecraft mob" },
          { id: ",S-1HChnY", valor: "Base Hit Recovery OnKnees Izquierda 02 Minecraft mob" },
          { id: "S+fL.0UD*", valor: "Base Hit Recovery OnKnees Izquierda Minecraft mob" },
          { id: "1W1PcCqzn", valor: "Base Hit Recovery PushUp Adelante Minecraft mob" },
          { id: "lG.4ZP9Vb", valor: "Base Hit Recovery PushUp Atras Minecraft mob" },
          { id: "wZSZRMUeU", valor: "Base Hit Recovery PushUp Derecha Minecraft mob" },
          { id: "1UVviaE;B", valor: "Base Hit Recovery PushUp Izquierda Minecraft mob" },
          { id: "0+XTf-FD1", valor: "Base Hit Recovery SitUp Derecha Minecraft mob" },
          { id: "xbkSiKOK,", valor: "Base Hit Recovery SitUp Izquierda Minecraft mob" },
          { id: "-YEOnJ9T2", valor: "Base Hit Stun End 02 Minecraft mob" },
          { id: "P,Oy:Nwbs", valor: "Base Hit Stun End 03 Minecraft mob" },
          { id: "r;sV+RnaJ", valor: "Base Hit Stun End Minecraft mob" },
          { id: "BPH;cUPHi", valor: "Base Hit Stun Into 02 Minecraft mob" },
          { id: ";jMLFHzTE", valor: "Base Hit Stun Into 03 Minecraft mob" },
          { id: "W6EyJ8F-*", valor: "Base Hit Stun Light Minecraft mob" },
          { id: "z3br1aer0", valor: "Base Hit Stun Loop 02 Minecraft mob" },
          { id: "-YE,-pw8d", valor: "Base Hit Stun Loop 03 Minecraft mob" },
          { id: "unZUN23KT", valor: "Base Hit Stun Loop Minecraft mob" },
          { id: "/Ip-4FYxE", valor: "Base Hit Stun Med Minecraft mob" },
        ]
      },
      {
        nombre: "Mixamo",
        data: [
          { id: "y-I-ZxeYA", valor: "ZombieArrastrar Minecraft mob" },
          { id: "d8T6vbVj9", valor: "ZombieAtacar Minecraft mob" },
          { id: "Pa0OM;V7Z", valor: "ZombieAtaque Minecraft mob" },
          { id: "ixVNOiM5,", valor: "ZombieAtaque2 Minecraft mob" },
          { id: "1G8/0ZRce", valor: "ZombieCaminar Minecraft mob" },
          { id: "AzalIT81D", valor: "ZombieCaminar2 Minecraft mob" },
          { id: "D_dzlQTfJ", valor: "ZombieCaminar3 Minecraft mob" },
          { id: "+LOKU_GK/", valor: "ZombieCaminar4 Minecraft mob" },
          { id: "*d.80KwDF", valor: "ZombieComerPiso Minecraft mob" },
          { id: "dMWWoR5f3", valor: "ZombieCorrer Minecraft mob" },
          { id: "eNyQBobnP", valor: "ZombieDeath Minecraft mob" },
          { id: "CIA4CNACM", valor: "ZombieDeath2 Minecraft mob" },
          { id: "Jact7Vz_,", valor: "ZombieDesesperar Minecraft mob" },
          { id: "/kw/Bn80f", valor: "ZombieEnloquece Minecraft mob" },
          { id: "*q,H;vAiJ", valor: "ZombieGolpear Minecraft mob" },
          { id: "+tQx8UtzV", valor: "ZombieGolpear2 Minecraft mob" },
          { id: "dB2yDRVDQ", valor: "ZombieGolpear3 Minecraft mob" },
          { id: "C.WcCKe1r", valor: "ZombieGrito Minecraft mob" },
          { id: "c2Ez_d5bz", valor: "ZombieIdle Minecraft mob" },
          { id: "R;T9ncqif", valor: "ZombieIdle2 Minecraft mob" },
          { id: "6Ms,nBcht", valor: "ZombieIdle3 Minecraft mob" },
          { id: "p4VI9/Hyv", valor: "ZombieIdle4 Minecraft mob" },
          { id: "XuXpcjF83", valor: "ZombieIdle5 Minecraft mob" },
          { id: "kOb5+1aX4", valor: "ZombieIdle6 Minecraft mob" },
          { id: "yxXYs-fw_", valor: "ZombieLevantar Minecraft mob" },
          { id: "-h2h-a8Kc", valor: "ZombieLevantar2 Minecraft mob" },
          { id: "9TB-XTlis", valor: "ZombieLevantarse Minecraft mob" },
          { id: "oPzF8KEN9", valor: "ZombieMorir Minecraft mob" },
          { id: "w55qsc3/v", valor: "ZombiePatada Minecraft mob" },
          { id: "nVgsqJ4.i", valor: "ZombiePatada2 Minecraft mob" },
          { id: "a;WluO5dy", valor: "ZombiePonerseComer Minecraft mob" },
          { id: "Bs,7:oIGt", valor: "ZombiePrepararAtaque Minecraft mob" },
          { id: "jzC6Pi-9h", valor: "ZombiePunete Minecraft mob" },
          { id: "H;EU3Bdd2", valor: "ZombieRascarse Minecraft mob" },
          { id: "l-XxsoW7:", valor: "ZombieVoltear Minecraft mob" },
        ]
      },
      /*{
        nombre: "San Andreas", 
      },
      {
        nombre: "Pubg Mobil", 
      },
      {
        nombre: "Final Fantasy", 
      },
      {
        nombre: "Big Rumble Boxing", 
      },
      {
        nombre: "Life is Strange", 
      },
      {
        nombre: "Fortnite", 
      },
      {
        nombre : "Futbol",
      },
      {
        nombre: "eFootball", 
      },*/
      /*{
        nombre: "General", 
        data: []
      },*/
    ];

    let arrayCategoria = [
    { nombre: "Head", data: ["Cabeza", "Craneo", "Head"] },
    { nombre: "Talk", data: ["Talk", "Chat", "Say", "Converse", "Dialogue", "Conversando", "Hablar"] },
    { nombre: "Fly", data: ["Vuelo", "Aire", "Fly", "Flying","Air","Air", "Jump", "Aerial", "Fly", "Float", "Aire", "Salto", "Aéreo", "Volar"] },
    { nombre: "Idle", data: ["Idle", "Quieto", "Reposo", "Rest", "Wait", "Still", "Standby", "Pause","Inactivo", "Reposo", "Quieto"] },
    { nombre: "Weapon", data: ["Weapon", "Arma", "Pistola", "Escopeta","Metralleta","Cuchillo","Rifle"] },
    { nombre: "Interact", data: ["Interact", "Objeto", "Arma", "Escopeta","Metralleta","Cuchillo","Pistola","Use", "Activate", "Grab", "Press", "Manipulate","Interactuar", "Usar", "Tocar", "Activar","Bate"] },
    { nombre: "Hit", data: ["Golpear", "ATK", "Finish", "Pow", "Attack","Patada","Hit", "Strike", "Impact", "Blow", "Smash", "Punch","Golpe", "Impacto", "Puñetazo", "Strike", "Punch", "Smash", "Impact"]},
    { nombre: "Walk", data: ["Walk", "Caminar", "Caminata", "Andar", "Pasear", "Stroll", "Pace", "Step"] },
    { nombre: "Run", data: ["Run", "Sprint", "Dash", "Race", "Hustle","Sprint", "Jog", "Dash", "Rush" , "Correr", "Trotar", "Apresurarse"] },
    { nombre: "Recovery", data: ["Recovery", "Heal", "Regain", "Restore", "GetUp", "StandUp", "Recuperación", "Sanar", "Levantarse","Heal", "Regain", "GetUp"] },
    { nombre: "Stun", data: ["Stun", "Daze", "Knockback", "Freeze", "Dizzy", "Paralyze", "Aturdir", "Tambalear", "Desorientar","Dazed", "Knockback", "Stagger"] },
    { nombre: "Combat", data: ["Combat", "Fight", "Battle", "Melee", "Brawl", "Engage", "Combate", "Pelea","Fight", "Battle", "Engage","Combate", "Pelea", "Lucha"] },
    { nombre: "Death", data: ["Death", "Die", "Dead", "Kill", "Finish", "Downed", "Muerte", "Caer", "Fallecer", "Die", "Fall", "Collapse", "Perish"] },
    { nombre: "Combos", data: ["Combos", "Chains", "Sequences", "Attacks", "Move Set","Combo", "Chain"] },
    { nombre: "Shoot", data: ["Shoot", "Fire", "Blast", "Gun", "Aim", "Disparar", "Blast", "Gunfire"] },
    { nombre: "Climb", data: ["Climb", "Scale", "Ascend", "Mount", "CrawlUp", "Escalar", "Trepar", "Subir"] },
    { nombre: "GetShot", data: ["GetShot", "TakeHit", "Damaged", "HitReaction", "ImpactReceived", "Recibir Disparo", "Ser golpeado", "Herido", "Hit", "TakeDamage", "Injured", "Impact"] },
    { nombre: "Emotes", data: ["Expressions", "Gestures", "Reactions","Gestos", "Emociones", "Reacciones"] },
    { nombre: "Dance", data: ["Dance", "Move", "Groove", "Boogie", "Bailar", "Moverse", "Danza", "Dancing", "dnce"] },
    { nombre: "Launch", data: ["Lanzar", "Impulsar", "Arrojar","Throw", "Propel", "Toss"] },
    { nombre: "Loop", data: ["Bucle", "Ciclo", "Repetición", "Cycle", "Repeat", "Looping", "Loop"] },
    { nombre: "Zombie", data: ["Zombie", "Zombi", "Muertos"] },
    { nombre: "Vehiculo", data: ["Accidente", "Carro", "Atropello", "Bus", "Driver", "Taxi"] },
    { nombre: "Land", data: ["Land", "Suelo", "Piso", "Tierra"] },
    { nombre: "Listen", data: ["Listen", "Escuchar", "Oir", "Oido", "Tune in", "Hea", "Pay attention"] }
    ];