// --- Datos (sin cambios) ---
    const modelosTipo = ["San Andreas"];
        //const arraySex = ["Masculino", "Femenino", "N/A"];
        //Especial  Pandilla    Zombie  Peaton  Oficio  Policia 
    const modelos = [
        {nombre:"army rel", tipo:"San Andreas", categoria:"Zombie, Policia", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"BALLAS1 rel", tipo:"San Andreas", categoria:"Zombie, Pandilla", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"BALLAS2 rel", tipo:"San Andreas", categoria:"Zombie, Pandilla", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"BALLAS3 rel", tipo:"San Andreas", categoria:"Zombie, Pandilla", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"BFORI rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"BFOST rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"BFYBE rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"BFYBU rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"BFYPRO rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"BFYRI rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},

        {nombre:"BFYST rel", tipo:"San Andreas", categoria:"Peaton", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"BIKERA rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"BIKERB rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"BMOBAR rel", tipo:"San Andreas", categoria:"Zombie, Oficio", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"BMOCD rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"BMOCHIL rel", tipo:"San Andreas", categoria:"Zombie, Oficio", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"BMORI rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"BMOSEC rel", tipo:"San Andreas", categoria:"Zombie, Oficio", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"BMOST rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"BMOTR1 rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},

        {nombre:"BMYAP rel", tipo:"San Andreas", categoria:"Oficio", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"BMYBAR rel", tipo:"San Andreas", categoria:"Oficio", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"BMYBE rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"BMYBOUN rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"BMYBU rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"BMYCG rel", tipo:"San Andreas", categoria:"Zombie, Oficio", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"BMYCON rel", tipo:"San Andreas", categoria:"Zombie, Oficio", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"BMYCR rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"BMYDJ rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"BMYDRUG rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},

        {nombre:"BMYMIB rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"BMYMOUN rel", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"BMYPIMP rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"BMYPOL1 rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"BMYPOL2 rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"BMYRI rel", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"BMYST rel", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"BMYTATT rel", tipo:"San Andreas", categoria:"Oficio", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"COPGRL3 rel", tipo:"San Andreas", categoria:"Peaton", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"CROGRL3 rel", tipo:"San Andreas", categoria:"Oficio", sexo:"Femenino", rig:"ARPFortnite"},

        {nombre:"csher rel", tipo:"San Andreas", categoria:"Zombie, Policia", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"CWFOFR rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"CWFOHB rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"CWFYFR1 rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"CWFYFR2 rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"CWFYHB rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"CWMOFR rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"CWMOHB1 rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"CWMOHB2 rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"CWMYFR rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},

        {nombre:"CWMYHB1 rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"CWMYHB2 rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"DNB1 rel", tipo:"San Andreas", categoria:"Zombie, Pandilla", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"DNB2 rel", tipo:"San Andreas", categoria:"Zombie, Pandilla", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"DNB3 rel", tipo:"San Andreas", categoria:"Zombie, Pandilla", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"DNFOLC1 rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"DNFOLC2 rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"DNFYLC rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"DNMOLC1 rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"DNMOLC2 rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},

        {nombre:"DNMYLC rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"dsher rel", tipo:"San Andreas", categoria:"Zombie, Policia", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"DWFOLC rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"DWFYLC1 rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"DWFYLC2 rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"DWMOLC1 rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"DWMOLC2 rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"DWMYLC1 rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"DWMYLC2 rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"FAM1 rel", tipo:"San Andreas", categoria:"Zombie, Pandilla", sexo:"Masculino", rig:"ARPFortnite"},

        {nombre:"FAM2 rel", tipo:"San Andreas", categoria:"Zombie, Pandilla", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"FAM3 rel", tipo:"San Andreas", categoria:"Zombie, Pandilla", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"fbi rel", tipo:"San Andreas", categoria:"Zombie, Policia", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"GANGRL3 rel", tipo:"San Andreas", categoria:"Especial", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"GUNGRL3 rel", tipo:"San Andreas", categoria:"Peaton", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"HECK1 rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"HECK2 rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"HFORI rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"HFOST rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"HFYBE rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},

        {nombre:"HFYPRO rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"HFYRI rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"HFYST rel", tipo:"San Andreas", categoria:"Peaton", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"HMOGAR rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"HMORI rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"HMOST rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"HMYBE rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"HMYCM rel", tipo:"San Andreas", categoria:"Zombie, Oficio", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"HMYCR rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"HMYDRUG rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},

        {nombre:"HMYRI rel", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"HMYST rel", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"laemt1 rel", tipo:"San Andreas", categoria:"Oficio", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"lafd1 rel", tipo:"San Andreas", categoria:"Zombie, Oficio", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"lapd1 rel", tipo:"San Andreas", categoria:"Zombie, Policia", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"lapdm1 rel", tipo:"San Andreas", categoria:"Zombie, Policia", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"LSV1 rel", tipo:"San Andreas", categoria:"Zombie, Pandilla", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"LSV2 rel", tipo:"San Andreas", categoria:"Zombie, Pandilla", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"LSV3 rel", tipo:"San Andreas", categoria:"Zombie, Pandilla", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"lvemt1 rel", tipo:"San Andreas", categoria:"Oficio", sexo:"Masculino", rig:"ARPFortnite"},

        {nombre:"lvfd1 rel", tipo:"San Andreas", categoria:"Oficio, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"lvpd1 rel", tipo:"San Andreas", categoria:"Policia, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"MAFBOSS rel", tipo:"San Andreas", categoria:"Pandilla", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"MAFFA rel", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"MAFFB rel", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"MECGRL3 rel", tipo:"San Andreas", categoria:"Peaton", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"NURGRL3 rel", tipo:"San Andreas", categoria:"Peaton", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"OFORI rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"OFOST rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"OFYRI rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},

        {nombre:"OFYST rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"OMOBOAT rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"OMOKUNG rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"OMONOOD rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"OMORI rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"OMOST rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"OMYKARA rel", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"OMYRI rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"OMYST rel", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"SBFORI rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},

        {nombre:"SBFOST rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"SBFYPRO rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"SBFYRI rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"SBFYST rel", tipo:"San Andreas", categoria:"Peaton", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"SBFYSTR rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"SBMOCD rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"SBMORI rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"SBMOST rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"SBMOTR2 rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"SBMYCR rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},

        {nombre:"SBMYRI rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"SBMYST rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"SBMYTR3 rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"sfemt1 rel", tipo:"San Andreas", categoria:"Oficio", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"sffd1 rel", tipo:"San Andreas", categoria:"Oficio, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"sfpd1 rel", tipo:"San Andreas", categoria:"Policia, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"SFR1 rel", tipo:"San Andreas", categoria:"Pandilla", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"SFR2 rel", tipo:"San Andreas", categoria:"Pandilla", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"SFR3 rel", tipo:"San Andreas", categoria:"Pandilla", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"SFYPRO rel", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Femenino", rig:"ARPFortnite"},

        {nombre:"SHFYPRO rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"SHMYCR rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"SMYST rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"SMYST2 rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"SOFORI rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"SOFOST rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"SOFYBU rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"SOFYRI rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"SOFYST rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"SOMOBU rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        
        {nombre:"SOMORI rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"SOMOST rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"SOMYBU rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"SOMYRI rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"SOMYST rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"swat rel", tipo:"San Andreas", categoria:"Policia, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"SWFOPRO rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"SWFORI rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"SWFOST rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"SWFYRI rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},

        {nombre:"SWFYST rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"SWFYSTR rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"SWMOCD rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"SWMORI rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"SWMOST rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"SWMOTR1 rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"SWMOTR2 rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"SWMOTR3 rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"SWMOTR4 rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"SWMOTR5 rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},

        {nombre:"SWMYCR rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"SWMYHP1 rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"SWMYHP2 rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"SWMYRI rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"SWMYST rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"TRIADA rel", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"TRIADB rel", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"TRIBOSS rel", tipo:"San Andreas", categoria:"Pandilla", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"VBFYCRP rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"VBFYPRO rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},

        {nombre:"VBFYST2 rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"VBMOCD rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"VBMYBOX rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"VBMYCR rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"VBMYELV rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"VHFYPRO rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"VHFYST3 rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"VHMYCR rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"VHMYELV rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"VIMYELV rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},

        {nombre:"VLA1 rel", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"VLA2 rel", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"VLA3 rel", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"VMAFF1 rel", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"VMAFF2 rel", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"VMAFF3 rel", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"VMAFF4 rel", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"VWFYCRP rel", tipo:"San Andreas", categoria:"Peaton", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"VWFYPRO rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"VWFYST1 rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},

        {nombre:"VWFYWA2 rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"VWFYWAI rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"VWMOTR1 rel", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"VWMOTR2 rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"VWMYBJD rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"VWMYBOX rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"VWMYCD rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"VWMYCR rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WBDYG1 rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WBDYG2 rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},

        {nombre:"WFORI rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"WFOST rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"WFYBE rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"WFYBU rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"WFYBURG rel", tipo:"San Andreas", categoria:"Oficio, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"WFYCLOT rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"WFYCRK rel", tipo:"San Andreas", categoria:"Oficio", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"WFYJG rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"WFYLG rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"WFYPRO rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},

        {nombre:"WFYRI rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"WFYRO rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"WFYSEX rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"WFYST rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"WFYSTEW rel", tipo:"San Andreas", categoria:"Peaton", sexo:"Femenino", rig:"ARPFortnite"},
        {nombre:"WMOICE rel", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMOMIB rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMOPJ rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMOPREA rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMORI rel", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},

        {nombre:"WMOSCI rel", tipo:"San Andreas", categoria:"Oficio, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMOST rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMOTR1 rel", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMYAMMO rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMYBAR rel", tipo:"San Andreas", categoria:"Oficio, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMYBE rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMYBELL rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMYBMX rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMYBOUN rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMYBP rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},

        {nombre:"WMYBU rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMYCD1 rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMYCH rel", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMYCLOT rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMYCON rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMYCONB rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMYCR rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMYDRUG rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMYGOL1 rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMYGOL2 rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},

        {nombre:"WMYJG rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMYKARA rel", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMYLG rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMYMECH rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMYMOUN rel", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMYPIZZ rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMYPLT rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMYRI rel", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMYRO rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMYSGRD rel", tipo:"San Andreas", categoria:"Policia, Zombie", sexo:"Masculino", rig:"ARPFortnite"},

        {nombre:"WMYST rel", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"WMYVA rel", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},





        

        {nombre:"Zombie 1 rel", tipo:"San Andreas", categoria:"Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Zombie 2 rel", tipo:"San Andreas", categoria:"Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Zombie 3 rel", tipo:"San Andreas", categoria:"Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Zombie 4 rel", tipo:"San Andreas", categoria:"Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Zombie 5 rel", tipo:"San Andreas", categoria:"Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Zombie 6 rel", tipo:"San Andreas", categoria:"Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Zombie 7 rel", tipo:"San Andreas", categoria:"Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Zombie 8 rel", tipo:"San Andreas", categoria:"Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Zombie 9 rel", tipo:"San Andreas", categoria:"Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Zombie 10 rel", tipo:"San Andreas", categoria:"Zombie", sexo:"Masculino", rig:"ARPFortnite"},
        {nombre:"Zombie 11 rel", tipo:"San Andreas", categoria:"Zombie", sexo:"Masculino", rig:"ARPFortnite"},




        

    ];
        /*for (let i = 1; i <= 50; i++) {
            let tipo, sexoDeterminado, categoriaEjemplo;
            const tipoIndex = i % modelosTipo.length;
            tipo = modelosTipo[tipoIndex];
            if (i % 3 === 0) sexoDeterminado = "N/A";
            else if (i % 2 === 0) sexoDeterminado = "Masculino";
            else sexoDeterminado = "Femenino";
            const catsBase = ["Aventura", "Acción", "Estrategia", "Puzzle", "Deporte", "Construcción", "Misterio", "Principal", "Secundario", "Jugador"];
            if (i % 4 === 0) categoriaEjemplo = `${catsBase[i%catsBase.length]}, ${catsBase[(i+1)%catsBase.length]}`;
            else if (i % 4 === 1) categoriaEjemplo = catsBase[i%catsBase.length];
            else if (i % 4 === 2) categoriaEjemplo = `${catsBase[i%catsBase.length]}, ${catsBase[(i+2)%catsBase.length]}, ${catsBase[(i+3)%catsBase.length]}`;
            else categoriaEjemplo = "General";
            modelos.push({ nombre: `Personaje${i}`, tipo: tipo, categoria: categoriaEjemplo, sexo: sexoDeterminado, rig: `RigDemo${i % 3}` });
        }*/
