// --- DATOS ---
const arrayTipos = ["Tierra", "Aire", "Mar"];
const arrayCategorias = [
    { categoria: "Autos compactos y de 2 puertas", tipo: "Tierra" },
    { categoria: "Autos de carreras callejeras", tipo: "Tierra" },
    { categoria: "Autos lujosos y de 4 puertas", tipo: "Tierra" },
    { categoria: "Camiones pesados y vehiculos utilitarios", tipo: "Tierra" },
];
const arrayImagenes = [
    {
        nombre: "Tierra", data: [
            { nombre: "alpha", categoria: "Autos compactos y de 2 puertas", estado: "ambos" },
            { nombre: "blistac", categoria: "Autos compactos y de 2 puertas", estado: "ambos" },
            { nombre: "bravura", categoria: "Autos compactos y de 2 puertas", estado: "ambos" },
            { nombre: "buccanee", categoria: "Autos compactos y de 2 puertas", estado: "ambos" },
            { nombre: "cadrona", categoria: "Autos compactos y de 2 puertas", estado: "ambos" },
            { nombre: "club", categoria: "Autos compactos y de 2 puertas", estado: "ambos" },
            { nombre: "esperant", categoria: "Autos compactos y de 2 puertas", estado: "ambos" },
            { nombre: "euros", categoria: "Autos compactos y de 2 puertas", estado: "ambos" },
            { nombre: "feltzer", categoria: "Autos compactos y de 2 puertas", estado: "ambos" },
            { nombre: "fortune", categoria: "Autos compactos y de 2 puertas", estado: "ambos" },
            { nombre: "hermes", categoria: "Autos compactos y de 2 puertas", estado: "ambos" },
            { nombre: "hustler", categoria: "Autos compactos y de 2 puertas", estado: "ambos" },
            { nombre: "majestic", categoria: "Autos compactos y de 2 puertas", estado: "ambos" },
            { nombre: "manana", categoria: "Autos compactos y de 2 puertas", estado: "ambos" },
            { nombre: "picador", categoria: "Autos compactos y de 2 puertas", estado: "ambos" },
            { nombre: "previon", categoria: "Autos compactos y de 2 puertas", estado: "ambos" },
            { nombre: "stallion", categoria: "Autos compactos y de 2 puertas", estado: "ambos" },
            { nombre: "tampa", categoria: "Autos compactos y de 2 puertas", estado: "ambos" },
            { nombre: "virgo", categoria: "Autos compactos y de 2 puertas", estado: "ambos" },
            { nombre: "banshee", categoria: "Autos de carreras callejeras", estado: "ambos" },
            { nombre: "bullet", categoria: "Autos de carreras callejeras", estado: "ambos" },
            { nombre: "cheetah", categoria: "Autos de carreras callejeras", estado: "ambos" },
            { nombre: "comet", categoria: "Autos de carreras callejeras", estado: "ambos" },
            { nombre: "elegy", categoria: "Autos de carreras callejeras", estado: "ambos" },
            { nombre: "flash", categoria: "Autos de carreras callejeras", estado: "ambos" },
            { nombre: "hotknife", categoria: "Autos de carreras callejeras", estado: "ambos" },
            { nombre: "hotrina", categoria: "Autos de carreras callejeras", estado: "ambos" },
            { nombre: "hotrinb", categoria: "Autos de carreras callejeras", estado: "ambos" },
            { nombre: "hotring", categoria: "Autos de carreras callejeras", estado: "ambos" },
            { nombre: "infernus", categoria: "Autos de carreras callejeras", estado: "ambos" },
            { nombre: "jester", categoria: "Autos de carreras callejeras", estado: "ambos" },
            { nombre: "stratum", categoria: "Autos de carreras callejeras", estado: "ambos" },
            { nombre: "sultan", categoria: "Autos de carreras callejeras", estado: "ambos" },
            { nombre: "supergt", categoria: "Autos de carreras callejeras", estado: "ambos" },
            { nombre: "turismo", categoria: "Autos de carreras callejeras", estado: "ambos" },
            { nombre: "uranus", categoria: "Autos de carreras callejeras", estado: "ambos" },
            { nombre: "windsor", categoria: "Autos de carreras callejeras", estado: "ambos" },
            { nombre: "zr350", categoria: "Autos de carreras callejeras", estado: "ambos" },
            { nombre: "admiralf", categoria: "Autos lujosos y de 4 puertas", estado: "ambos" },
            { nombre: "elegantf", categoria: "Autos lujosos y de 4 puertas", estado: "ambos" },
            { nombre: "emperorf", categoria: "Autos lujosos y de 4 puertas", estado: "ambos" },
            { nombre: "glendalef", categoria: "Autos lujosos y de 4 puertas", estado: "ambos" },
            { nombre: "glenshitf", categoria: "Autos lujosos y de 4 puertas", estado: "ok" },
            { nombre: "greenwoof", categoria: "Autos lujosos y de 4 puertas", estado: "ambos" },
            { nombre: "intruderf", categoria: "Autos lujosos y de 4 puertas", estado: "ambos" },
            { nombre: "meritf", categoria: "Autos lujosos y de 4 puertas", estado: "ambos" },
            { nombre: "nebulaf", categoria: "Autos lujosos y de 4 puertas", estado: "ambos" },
            { nombre: "oceanicf", categoria: "Autos lujosos y de 4 puertas", estado: "ambos" },
            { nombre: "premierf", categoria: "Autos lujosos y de 4 puertas", estado: "ambos" },
            { nombre: "primof", categoria: "Autos lujosos y de 4 puertas", estado: "ambos" },
            { nombre: "sentinelf", categoria: "Autos lujosos y de 4 puertas", estado: "ambos" },
            { nombre: "staffordf", categoria: "Autos lujosos y de 4 puertas", estado: "ambos" },
            { nombre: "stretchf", categoria: "Autos lujosos y de 4 puertas", estado: "ambos" },
            { nombre: "sunrisef", categoria: "Autos lujosos y de 4 puertas", estado: "ambos" },
            { nombre: "tahomaf", categoria: "Autos lujosos y de 4 puertas", estado: "ambos" },
            { nombre: "vincentf", categoria: "Autos lujosos y de 4 puertas", estado: "ambos" },
            { nombre: "washingf", categoria: "Autos lujosos y de 4 puertas", estado: "ambos" },
            { nombre: "willardf", categoria: "Autos lujosos y de 4 puertas", estado: "ambos" },
            { nombre: "benson", categoria: "Camiones pesados y vehiculos utilitarios", estado: "ambos" },
            { nombre: "boxburg", categoria: "Camiones pesados y vehiculos utilitarios", estado: "ambos" },
            { nombre: "boxville", categoria: "Camiones pesados y vehiculos utilitarios", estado: "ambos" },
            { nombre: "cement", categoria: "Camiones pesados y vehiculos utilitarios", estado: "ambos" },
            { nombre: "combine", categoria: "Camiones pesados y vehiculos utilitarios", estado: "ok" },
            { nombre: "dft30", categoria: "Camiones pesados y vehiculos utilitarios", estado: "ambos" },
            { nombre: "dozer", categoria: "Camiones pesados y vehiculos utilitarios", estado: "nada" },
            { nombre: "dumper", categoria: "Camiones pesados y vehiculos utilitarios", estado: "ok" },
            { nombre: "duneride", categoria: "Camiones pesados y vehiculos utilitarios", estado: "ambos" },
            { nombre: "flatbed", categoria: "Camiones pesados y vehiculos utilitarios", estado: "ambos" },
            { nombre: "hotdog", categoria: "Camiones pesados y vehiculos utilitarios", estado: "ambos" },
            { nombre: "linerun", categoria: "Camiones pesados y vehiculos utilitarios", estado: "ambos" },
            { nombre: "mrwhoop", categoria: "Camiones pesados y vehiculos utilitarios", estado: "ambos" },
            { nombre: "mule", categoria: "Camiones pesados y vehiculos utilitarios", estado: "ambos" },
            { nombre: "packer", categoria: "Camiones pesados y vehiculos utilitarios", estado: "ambos" },
            { nombre: "petro", categoria: "Camiones pesados y vehiculos utilitarios", estado: "ambos" },
            { nombre: "rdtrain", categoria: "Camiones pesados y vehiculos utilitarios", estado: "ambos" },
            { nombre: "tractor", categoria: "Camiones pesados y vehiculos utilitarios", estado: "ambos" },
            { nombre: "yankee", categoria: "Camiones pesados y vehiculos utilitarios", estado: "ambos" }
        ]
    },
    {
        nombre: "Aire", data: [
        ]
    },
    {
        nombre: "Mar", data: [
        ]
    },
];
