const arrayPropiedad = [
    { nombre: "Dead Island 2", data: [
        "Base Context Head ChopPull ToD",
        "Base Context Head ChopPull ToD Med1HChL",
        "Base Context Head ChopPull ToD Med1HChR",
        "Base Context Head ChopPull ToR",
        "Base Context Head HugeHit ToD",
        "Base Context Head HugeHit ToD Long2H Swe R erM",
        "Base Context Head HugeHit ToD Slicing L",
        "Base Context Head HugeHit ToD Slicing R",
        "Base Context Head HugeHit ToD Weighty2HSwe L e",
        "Base Context Head HugeHit ToD Weighty2HSwe R e",
        "Base Context Head StabThrow ToDL",
        "Base Context Head StabThrow ToDR",
        "Base Context Stomach ChopPull ToL",
        "Base Context Stomach ChopPull ToL 1HM Ar",
        "Base Context Stomach ChopPull ToR",
        "Base Context Stomach ChopPull ToUR",
        "Base Context Stomach HugeHit ToL",
        "Base Context Stomach HugeHit ToL Rake Ar",
        "Base Context Stomach HugeHit ToR",
        "Base Context Stomach HugeHit ToR Rake Ar",
        "Base Context Stomach HugeHit ToU L",
        "Base Context Stomach HugeHit ToU R",
        "Base Context Stomach HugeStabSlash ToL A",
        "Base Context Stomach StabThrow ToL",
        "Base Context Stomach StabThrow ToR",
        "Key|sweet.qc skeleton|sweet ragdoll.001",
        "Paired Base Context Head Knife ToL",
        "Paired Base Context Head StabSlash ToU A",
        "Paired Base Context Stomach StabSlash ToR erMa",
        "Paired Base Context Stomach StabSlash ToU S1H",
        "Paired Context FistSweeping Head L",
        "Paired Context FistSweeping Head R",
        "Paired Context FistSweeping Stomach L Ar",
        "Paired Context FistSweeping Stomach R Ar",
        "Paired Context Head ChopPull ToD Med2HChL erMa",
        "Paired Context Head ChopPull ToD Med2HChR erMa",
        "Paired Context Head HugeHit ToL",
        "Paired Context Head HugeHit ToR",
        "Paired Context Head ImpaleDrop L",
        "Paired Context Head ImpaleDrop R",
        "Paired Context Head Slash ToL",
        "Paired Context Head Slash ToR",
        "Paired Context Long2HStabbing Head L Arm",
        "Paired Context Long2HStabbing Stomach L",
        "Paired Context Stomach ChopPull ToR Med2HChL e",
        "Paired Context Stomach ClawsImpaleDrop L erMal",
        "Paired Context Stomach ClawsImpaleDrop R erMal",
        "Paired Context Stomach Crescent ImpaleDrop L e",
        "Paired Context Stomach Crescent ImpaleDrop R e",
        "Paired Context Stomach ImpaleDrop L Army",
        "Paired Context Stomach ImpaleDrop R Army",
        "Paired Context Stomach Slash ToL",
        "Paired Context Stomach StabSlash ToU Med2HChU",
        "Base Hit Air Adelante Inicio",
        "Base Hit Air Adelante Loop Fast",
        "Base Hit Air Adelante Loop Slow",
        "Base Hit Air Adelante Suelo",
        "Base Hit Air Atras Inicio",
        "Base Hit Air Atras Loop Fast",
        "Base Hit Air Atras Loop Slow",
        "Base Hit Air Atras Suelo",
        "Base Hit Air Derecha Inicio",
        "Base Hit Air Derecha Loop Fast",
        "Base Hit Air Derecha Loop Slow",
        "Base Hit Air Derecha Suelo",
        "Base Hit Air Izquierda Inicio",
        "Base Hit Air Izquierda Loop Fast",
        "Base Hit Air Izquierda Loop Slow",
        "Base Hit Air Izquierda Suelo",
        "Base Hit Launch ArmL Adelante",
        "Base Hit Launch ArmL Atras",
        "Base Hit Launch ArmR Adelante",
        "Base Hit Launch ArmR Atras",
        "Base Hit Launch LegL Adelante",
        "Base Hit Launch LegL Atras",
        "Base Hit Launch LegL Derecha",
        "Base Hit Launch LegL Izquierda",
        "Base Hit Launch LegR Adelante",
        "Base Hit Launch LegR Atras",
        "Base Hit Launch LegR Derecha",
        "Base Hit Launch LegR Izquierda",
        "Base Hit Launch Stomach Abajo",
        "Base Hit Launch Stomach Adelante",
        "Base Hit Launch Stomach Atras",
        "Base Hit Launch Stomach Derecha",
        "Base Hit Launch Stomach Izquierda",
        "Base Hit Launch Torso Abajo",
        "Base Hit Launch Torso Adelante",
        "Base Hit Launch Torso Arriba",
        "Base Hit Launch Torso Atras",
        "Base Hit Launch Torso Derecha",
        "Base Hit Launch Torso Izquierda",
        "Base Hit Suelo Adelante Light Arriba",
        "Base Hit Suelo Adelante Light Arriba  02",
        "Base Hit Suelo Adelante Light Derecha",
        "Base Hit Suelo Adelante Light Izquierda",
        "Base Hit Suelo Atras Light Arriba",
        "Base Hit Suelo Atras Light Arriba  02",
        "Base Hit Suelo Atras Light Derecha",
        "Base Hit Suelo Atras Light Izquierda",
        "Crawler Hit Suelo Adelante Light Arriba",
        "Crawler Hit Suelo Adelante Light Derecha",
        "Crawler Hit Suelo Adelante Light Izquierda",
        "Crawler Hit Suelo Atras Light Arriba",
        "Crawler Hit Suelo Atras Light Arriba  02",
        "Crawler Hit Suelo Atras Light Derecha",
        "Crawler Hit Suelo Atras Light Izquierda",
        "Base Hit Light ArmL Adelante",
        "Base Hit Light ArmL Adelante 02",
        "Base Hit Light ArmL Atras",
        "Base Hit Light ArmL Atras 02",
        "Base Hit Light ArmL Derecha",
        "Base Hit Light ArmL Derecha 02",
        "Base Hit Light ArmL Izquierda",
        "Base Hit Light ArmL Izquierda 02",
        "Base Hit Light ArmR Adelante",
        "Base Hit Light ArmR Adelante 02",
        "Base Hit Light ArmR Atras",
        "Base Hit Light ArmR Atras 02",
        "Base Hit Light ArmR Derecha",
        "Base Hit Light ArmR Derecha 02",
        "Base Hit Light ArmR Izquierda",
        "Base Hit Light ArmR Izquierda 02",
        "Base Hit Light Head Abajo",
        "Base Hit Light Head Abajo 02",
        "Base Hit Light Head Adelante",
        "Base Hit Light Head Adelante 02",
        "Base Hit Light Head Arriba",
        "Base Hit Light Head Arriba 02",
        "Base Hit Light Head Atras",
        "Base Hit Light Head Atras 02",
        "Base Hit Light Head Derecha",
        "Base Hit Light Head Derecha 02",
        "Base Hit Light Head Izquierda",
        "Base Hit Light Head Izquierda 02",
        "Base Hit Light LegL Adelante",
        "Base Hit Light LegL Adelante 02",
        "Base Hit Light LegL Atras",
        "Base Hit Light LegL Atras 02",
        "Base Hit Light LegL Derecha",
        "Base Hit Light LegL Derecha 02",
        "Base Hit Light LegL Izquierda",
        "Base Hit Light LegL Izquierda 02",
        "Base Hit Light LegR Adelante",
        "Base Hit Light LegR Adelante 02",
        "Base Hit Light LegR Atras",
        "Base Hit Light LegR Atras 02",
        "Base Hit Light LegR Derecha",
        "Base Hit Light LegR Derecha 02",
        "Base Hit Light LegR Izquierda",
        "Base Hit Light LegR Izquierda 02",
        "Base Hit Light Stomach Abajo",
        "Base Hit Light Stomach Abajo 02",
        "Base Hit Light Stomach Adelante",
        "Base Hit Light Stomach Adelante 02",
        "Base Hit Light Stomach Arriba",
        "Base Hit Light Stomach Arriba 02",
        "Base Hit Light Stomach Atras",
        "Base Hit Light Stomach Atras 02",
        "Base Hit Light Stomach Derecha",
        "Base Hit Light Stomach Derecha 02",
        "Base Hit Light Stomach Izquierda",
        "Base Hit Light Stomach Izquierda 02",
        "Base Hit Light Torso Abajo",
        "Base Hit Light Torso Abajo 02",
        "Base Hit Light Torso Adelante",
        "Base Hit Light Torso Adelante 02",
        "Base Hit Light Torso Arriba",
        "Base Hit Light Torso Arriba 02",
        "Base Hit Light Torso Atras",
        "Base Hit Light Torso Atras 02",
        "Base Hit Light Torso Derecha",
        "Base Hit Light Torso Derecha 02",
        "Base Hit Light Torso Izquierda",
        "Base Hit Light Torso Izquierda 02",
          "Base Hit Med ArmL Adelante",
          "Base Hit Med ArmL Atras",
          "Base Hit Med ArmL Derecha",
          "Base Hit Med ArmL Izquierda",
          "Base Hit Med ArmR Adelante",
          "Base Hit Med ArmR Atras",
          "Base Hit Med ArmR Derecha",
          "Base Hit Med ArmR Izquierda",
          "Base Hit Med Head Abajo",
          "Base Hit Med Head Adelante",
          "Base Hit Med Head Arriba",
          "Base Hit Med Head Atras",
          "Base Hit Med Head Derecha",
          "Base Hit Med Head Izquierda",
          "Base Hit Med LegL Adelante",
          "Base Hit Med LegL Atras",
          "Base Hit Med LegL Derecha",
          "Base Hit Med LegL Izquierda",
          "Base Hit Med LegR Adelante",
          "Base Hit Med LegR Atras",
          "Base Hit Med LegR Derecha",
          "Base Hit Med LegR Izquierda",
          "Base Hit Med Stomach Abajo",
          "Base Hit Med Stomach Adelante",
          "Base Hit Med Stomach Arriba",
          "Base Hit Med Stomach Atras",
          "Base Hit Med Stomach Derecha",
          "Base Hit Med Stomach Izquierda",
          "Base Hit Med Torso Abajo",
          "Base Hit Med Torso Adelante",
          "Base Hit Med Torso Arriba",
          "Base Hit Med Torso Atras",
          "Base Hit Med Torso Derecha",
          "Base Hit Med Torso Izquierda",
          "Base Hit Recovery Hunched Abajo",
          "Base Hit Recovery Hunched Abajo 02",
          "Base Hit Recovery Hunched Adelante",
          "Base Hit Recovery Hunched Adelante 02",
          "Base Hit Recovery Hunched Arriba",
          "Base Hit Recovery Hunched Arriba 02",
          "Base Hit Recovery Hunched Atras",
          "Base Hit Recovery Hunched Atras 02",
          "Base Hit Recovery Hunched Derecha",
          "Base Hit Recovery Hunched Derecha 02",
          "Base Hit Recovery Hunched Izquierda",
          "Base Hit Recovery Hunched Izquierda 02",
          "Base Hit Recovery OnFeet Abajo",
          "Base Hit Recovery OnFeet Abajo 02",
          "Base Hit Recovery OnFeet Adelante",
          "Base Hit Recovery OnFeet Adelante 02",
          "Base Hit Recovery OnFeet Atras",
          "Base Hit Recovery OnFeet Atras 02",
          "Base Hit Recovery OnFeet Derecha",
          "Base Hit Recovery OnFeet Derecha 02",
          "Base Hit Recovery OnFeet Izquierda",
          "Base Hit Recovery OnFeet Izquierda 02",
          "Base Hit Recovery OnFeet Legs Atras",
          "Base Hit Recovery OnKnees Abajo",
          "Base Hit Recovery OnKnees Abajo 02",
          "Base Hit Recovery OnKnees Adelante",
          "Base Hit Recovery OnKnees Adelante 02",
          "Base Hit Recovery OnKnees Atras",
          "Base Hit Recovery OnKnees Atras 02",
          "Base Hit Recovery OnKnees Derecha",
          "Base Hit Recovery OnKnees Derecha 02",
          "Base Hit Recovery OnKnees Izquierda",
          "Base Hit Recovery OnKnees Izquierda 02",
          "Base Hit Recovery PushUp Adelante",
          "Base Hit Recovery PushUp Atras",
          "Base Hit Recovery PushUp Derecha",
          "Base Hit Recovery PushUp Izquierda",
          "Base Hit Recovery SitUp Derecha",
          "Base Hit Recovery SitUp Izquierda",
          "Base Hit Stumble Light Head Abajo",
          "Base Hit Stumble Light Head Adelante",
          "Base Hit Stumble Light Head Arriba",
          "Base Hit Stumble Light Head Atras",
          "Base Hit Stumble Light Head Derecha",
          "Base Hit Stumble Light Head Izquierda",
          "Base Hit Stumble Light LegL Adelante",
          "Base Hit Stumble Light LegL Atras",
          "Base Hit Stumble Light LegL Derecha",
          "Base Hit Stumble Light LegL Izquierda",
          "Base Hit Stumble Light LegR Adelante",
          "Base Hit Stumble Light LegR Atras",
          "Base Hit Stumble Light LegR Derecha",
          "Base Hit Stumble Light LegR Izquierda",
          "Base Hit Stumble Light Stomach Abajo",
          "Base Hit Stumble Light Stomach Adelante",
          "Base Hit Stumble Light Stomach Arriba",
          "Base Hit Stumble Light Stomach Atras",
          "Base Hit Stumble Light Stomach Derecha",
          "Base Hit Stumble Light Stomach Izquierda",
          "Base Hit Stumble Light Torso Abajo",
          "Base Hit Stumble Light Torso Adelante",
          "Base Hit Stumble Light Torso Arriba",
          "Base Hit Stumble Light Torso Atras",
          "Base Hit Stumble Light Torso Derecha",
          "Base Hit Stumble Light Torso Izquierda",
          "Base Hit Stumble Med Head Abajo",
          "Base Hit Stumble Med Head Adelante",
          "Base Hit Stumble Med Head Arriba",
          "Base Hit Stumble Med Head Atras",
          "Base Hit Stumble Med Head Derecha",
          "Base Hit Stumble Med Head Izquierda",
          "Base Hit Stumble Med LegL Adelante",
          "Base Hit Stumble Med LegL Atras",
          "Base Hit Stumble Med LegL Derecha",
          "Base Hit Stumble Med LegL Izquierda",
          "Base Hit Stumble Med LegR Adelante",
          "Base Hit Stumble Med LegR Atras",
          "Base Hit Stumble Med LegR Derecha",
          "Base Hit Stumble Med LegR Izquierda",
          "Base Hit Stumble Med Stomach Abajo",
          "Base Hit Stumble Med Stomach Adelante",
          "Base Hit Stumble Med Stomach Arriba",
          "Base Hit Stumble Med Stomach Atras",
          "Base Hit Stumble Med Stomach Derecha",
          "Base Hit Stumble Med Stomach Izquierda",
          "Base Hit Stumble Med Torso Abajo",
          "Base Hit Stumble Med Torso Adelante",
          "Base Hit Stumble Med Torso Arriba",
          "Base Hit Stumble Med Torso Atras",
          "Base Hit Stumble Med Torso Derecha",
          "Base Hit Stumble Med Torso Izquierda",
          "Base Hit Stun End",
          "Base Hit Stun End 02",
          "Base Hit Stun End 03",
          "Base Hit Stun Into 02",
          "Base Hit Stun Into 03",
          "Base Hit Stun Light",
          "Base Hit Stun Loop",
          "Base Hit Stun Loop 02",
          "Base Hit Stun Loop 03",
          "Base Hit Stun Med"
    ] },
    { nombre: "Mixamo", data: [
        "DanceMixamo1",
        "DanceMixamo10",
        "DanceMixamo11",
        "DanceMixamo12",
        "DanceMixamo13",
        "DanceMixamo14",
        "DanceMixamo2",
        "DanceMixamo3",
        "DanceMixamo4",
        "DanceMixamo5",
        "DanceMixamo6",
        "DanceMixamo7",
        "DanceMixamo8",
        "DanceMixamo9",
        "Bouncing Fight Idle",
        "Fight Idle",
        "Fight Idle (1)",
        "Fight Idle To Standing Idle",
        "Fighting Idle",
        "Fireball",
        "Fist Fight A",
        "Fist Fight B",
        "Hell Slammer A",
        "Hell Slammer B",
        "Butterfly Twirl",
        "Chapa 2",
        "Drop Kick",
        "Flip Kick",
        "Flip Kick (1)",
        "Flying Bicycle Kick",
        "Flying Kick",
        "Goalkeeper Drop Kick",
        "Great Sword Kick",
        "Hurricane Kick",
        "Inside Crescent Kick",
        "Inverted Double Kick To Kip Up",
        "Kicking",
        "Kicking (1)",
        "Kicking (2)",
        "Kicking (3)",
        "Kicking (4)",
        "Kicking (5)",
        "Kicking (6)",
        "Kicking Out",
        "Mma Kick",
        "Mma Kick (1)",
        "Mma Kick (2)",
        "Mma Kick (3)",
        "Mma Kick (4)",
        "Mma Kick (5)",
        "Rifle Turn And Kick",
        "Roll Kicking",
        "Roundhouse Kick",
        "Side Kick",
        "Spin Flip Kick",
        "Zombie Kicking",
        "Run1",
        "Run10",
        "Run11",
        "Run12",
        "Run13",
        "Run14",
        "Run15",
        "Run16",
        "Run17",
        "Run18",
        "Run19",
        "Run2",
        "Run20",
        "Run21",
        "Run22",
        "Run23",
        "Run24",
        "Run25",
        "Run26",
        "Run27",
        "Run28",
        "Run29",
        "Run3",
        "Run30",
        "Run31",
        "Run32",
        "Run33",
        "Run34",
        "Run35",
        "Run36",
        "Run37",
        "Run38",
        "Run39",
        "Run4",
        "Run40",
        "Run41",
        "Run42",
        "Run43",
        "Run44",
        "Run45",
        "Run46",
        "Run47",
        "Run48",
        "Run49",
        "Run5",
        "Run50",
        "Run6",
        "Run7",
        "Run8",
        "Run9",
        "RunArma1",
        "RunArma10",
        "RunArma11",
        "RunArma12",
        "RunArma13",
        "RunArma14",
        "RunArma15",
        "RunArma16",
        "RunArma17",
        "RunArma18",
        "RunArma19",
        "RunArma2",
        "RunArma20",
        "RunArma21",
        "RunArma22",
        "RunArma23",
        "RunArma24",
        "RunArma25",
        "RunArma26",
        "RunArma27",
        "RunArma28",
        "RunArma29",
        "RunArma3",
        "RunArma30",
        "RunArma31",
        "RunArma32",
        "RunArma33",
        "RunArma34",
        "RunArma35",
        "RunArma36",
        "RunArma37",
        "RunArma38",
        "RunArma39",
        "RunArma4",
        "RunArma40",
        "RunArma41",
        "RunArma42",
        "RunArma43",
        "RunArma44",
        "RunArma45",
        "RunArma46",
        "RunArma47",
        "RunArma48",
        "RunArma49",
        "RunArma5",
        "RunArma50",
        "RunArma51",
        "RunArma52",
        "RunArma53",
        "RunArma6",
        "RunArma7",
        "RunArma8",
        "RunArma9",
        "HitAbdomen",
        "HitAbdomen2",
        "HitAbdomen3",
        "HitAtropellar",
        "HitAtropello",
        "HitBate",
        "HitCombo",
        "HitCombo2",
        "HitCorrer",
        "HitDisparando",
        "HitEstomago",
        "HitGolpeBajo",
        "HitHeadShoot",
        "HitMuerte",
        "HitMuerte2",
        "HitMuerte2.001",
        "HitPorAtras",
        "HitRostro",
        "HitShoot",
        "HitShoot2",
        "HitVolteretaAtras",
        "puenteCara",
        "ZombieArrastrar",
        "ZombieAtacar",
        "ZombieAtaque",
        "ZombieAtaque2",
        "ZombieCaminar",
        "ZombieCaminar2",
        "ZombieCaminar3",
        "ZombieCaminar4",
        "ZombieComerPiso",
        "ZombieCorrer",
        "ZombieDeath",
        "ZombieDeath2",
        "ZombieDesesperar",
        "ZombieEnloquece",
        "ZombieGolpear",
        "ZombieGolpear2",
        "ZombieGolpear3",
        "ZombieGrito",
        "ZombieIdle",
        "ZombieIdle2",
        "ZombieIdle3",
        "ZombieIdle4",
        "ZombieIdle5",
        "ZombieIdle6",
        "ZombieLevantar",
        "ZombieLevantar2",
        "ZombieLevantarse",
        "ZombieMorir",
        "ZombiePatada",
        "ZombiePatada2",
        "ZombiePonerseComer",
        "ZombiePrepararAtaque",
        "ZombiePunete",
        "ZombieRascarse",
        "ZombieVoltear"
    ] },
    { nombre: "San Andreas", data: [
      "bd_clap",
      "bd_clap1",
      "DAN_Down_A",
      "DAN_Left_A",
      "DAN_Loop_A",
      "DAN_Loop_A_remap.001",
      "DAN_Right_A",
      "DAN_Up_A",
      "dance_loop",
      "dnce_M_a",
      "dnce_M_b",
      "dnce_M_c",
      "dnce_M_d",
      "dnce_M_e"
    ] },
    {nombre: "Pubg Mobil", data:[
        "Special Emot Champion",
    "Lobby Emot Provocation B",
    "Lobby Emot Provocation A",
    "football win Emot shuaiquan",
    "Egypt Emot sitdown",
    "Egypt Emot Execution Hit",
    "Egypt Emot Execution Atk",
    "Dance Emot Vulgar novel",
    "Dance Emot TVman",
    "Dance Emot taishi 01",
    "Dance Emot shuaishouwu",
    "Dance Emot shuaiqunwu",
    "Dance Emot Rabbitdance",
    "Dance Emot qinwawu",
    "Dance Emot PulpFiction",
    "Dance Emot panama 01",
    "Dance Emot momoland 01",
    "Dance Emot jixiewu 02",
    "Dance Emot jixiewu 01",
    "Dance Emot jiewu 01",
    "Dance Emot Jacket996int",
    "Dance Emot Jacket932int",
    "Dance Emot Jacket896int",
    "Dance Emot Jacket863int",
    "Dance Emot Jacket783int",
    "Dance Emot Jacket505int",
    "Dance Emot Jacket168int",
    "Dance Emot Jacket1084int",
    "Dance Emot Jacket1051int",
    "Dance Emot Jacket 782 int",
    "Dance Emot Jacket 748 int",
    "Dance Emot haicao 01",
    "Dance Emot GaWu B",
    "Dance Emot GaWu A",
    "Dance Emot GAWU 6",
    "Dance Emot GAWU 5",
    "Dance Emot football win sangba",
    "Dance Emot football win dadianhua",
    "Dance Emot Emot KOEHAN",
    "Dance Emot Electric sound",
    "Dance Emot douxiongwu",
    "Dance Emot DouJianWu",
    "Dance Emot douhui 01",
    "Dance Emot Discocheer02",
    "Dance Emot Cossack dance",
    "Dance Emot chicken",
    "Dance Emot Avatar B0018",
    "Dance Emot Anniversary",
    "Dance Emot 3AR",
    "Dance Emot 180Dance",
    "Dance Emot 101 01",
    "Dance Emot 02 Jacket1080int",
    "Dance Emot 02 Jacket1078int",
    "Dance Emot 01 Jacket1078int",
    "Combat Emot Vampire",
    "Combat Emot Turn",
    "Combat Emot Suffocating",
    "Combat Emot Scorpion",
    "Combat Emot Pretend",
    "Combat Emot Laughter",
    "Combat Emot Keep silent",
    "Combat Emot Jacket936int",
    "Combat Emot Jacket826int",
    "Combat Emot Jacket814int",
    "Combat Emot Jacket792int",
    "Combat Emot Jacket724int",
    "Combat Emot Jacket180int",
    "Combat Emot Jacket179int",
    "Combat Emot Jacket1092int",
    "Combat Emot Howling",
    "Combat Emot Handstand",
    "Combat Emot HackerEmpire",
    "Combat Emot Front Spray",
    "Combat Emot Freed",
    "Combat Emot Collapse",
    "Combat Emot ChallengeAccept",
    "Combat Emot Aircraftcarrier style"
    ]},
    {nombre: "Final Fantasy", data:[
    "Win01",
    "WAttack13 0",
    "WAttack04 0",
    "WAttack03 0",
    "WAttack02 0",
    "WAttack01 0",
    "WalkR01 2r",
    "WalkR01 2l",
    "WalkR 01 1 Seq",
    "WalkR 01 0 Seq",
    "WalkL01 2r",
    "WalkL01 2l",
    "WalkL 01 1 Seq",
    "WalkL 01 0 Seq",
    "WalkFR01 1",
    "WalkFL01 1",
    "WalkBR01 1",
    "WalkBL01 1",
    "WalkB01 2r",
    "WalkB01 2l",
    "Walk01 2r",
    "Walk01 2l",
    "Walk01 1 Seq",
    "Walk01 1",
    "Walk01 0 Seq",
    "Walk01 0 R90",
    "Walk01 0 R180",
    "Walk01 0 L90",
    "Walk01 0 L180",
    "Walk01 0 L0",
    "Vision01 0",
    "Turn01 R90",
    "Turn01 R180",
    "Turn01 L90",
    "Turn01 L180",
    "SAttackJ13 0",
    "SAttackJ12 0",
    "SAttackJ03 0",
    "SAttackJ02 0",
    "SAttackJ 01 2 Seq",
    "SAttackJ 01 1 Seq",
    "SAttackJ 01 0 Seq",
    "SAttack13 0",
    "SAttack12 0",
    "SAttack03 0",
    "SAttack02 0",
    "SAttack01 0",
    "Run01 UP",
    "Run01 2r",
    "Run01 2l",
    "Run01 1 R180",
    "Run01 1 L180",
    "Run01 1",
    "Run01 0 R90",
    "Run01 0 R180",
    "Run01 0 L90",
    "Run01 0 L180",
    "Run01 0 L0",
    "NAttackJ16 0",
    "NAttackJ15 0",
    "NAttackJ14 0",
    "NAttackJ06 0",
    "NAttackJ05 0",
    "NAttackJ04 0",
    "NAttackJ03 0",
    "NAttackJ02 0",
    "NAttackJ01 0",
    "NAttack20 0",
    "NAttack16 0",
    "NAttack15 0",
    "NAttack14 0",
    "NAttack07 0",
    "NAttack06 0",
    "NAttack05 0",
    "NAttack04 0",
    "NAttack03 0",
    "NAttack02 0",
    "NAttack01 0",
    "MagSummon 01 4 Seq",
    "MagSummon 01 3 Seq",
    "MagSummon 01 2 Seq",
    "MagSummon 01 1 Seq",
    "MagSummon 01 0 Seq",
    "MagCure 01 2 Seq",
    "MagCure 01 1 Seq",
    "MagCure 01 0 Seq",
    "MagAttack 02 2 Seq",
    "MagAttack 02 1 Seq",
    "MagAttack 02 0 Seq",
    "MagAttack 01 2 Seq",
    "MagAttack 01 1 Seq",
    "MagAttack 01 0 Seq",
    "Key|sweet.qc skeleton|sweet ragdoll.001",
    "Jump01 0",
    "ItemCure01",
    "Item01",
    "Idle 01 2 Seq",
    "Idle 01 1 Seq",
    "Idle 01 0 Seq",
    "GuardFace 02 2 Seq",
    "GuardFace 02 1 Seq",
    "GuardFace 02 0 Seq",
    "GuardFace 01 2 Seq",
    "GuardFace 01 1 Seq",
    "GuardFace 01 0 Seq",
    "Guard 01 2 Seq",
    "Guard 01 1 Seq",
    "Guard 01 0 Seq",
    "Fall 01 3 Seq",
    "Fall 01 2 Seq",
    "Fall 01 1 Seq",
    "EleBurstJ01 0",
    "EleBurst01 0",
    "DownDieF01",
    "DownDieB01",
    "DownAbnormalF01 0",
    "DownAbnormalB01 0",
    "DmgUpperF 01 1 Seq",
    "DmgUpperF 01 0 Seq",
    "DmgUpper01 1 Seq",
    "DmgUpper01 0 Seq",
    "DmgStrikeF 01 1 Seq",
    "DmgStrikeF 01 0 Seq",
    "DmgStrike01 1 Seq",
    "DmgStrike01 0 Seq",
    "DmgReflect01",
    "DmgRecoverF01",
    "DmgRecoverB01",
    "DmgR01",
    "DmgL01",
    "DmgJGuard01",
    "DmgGuard03",
    "DmgGuard02",
    "DmgF02",
    "DmgF01",
    "DmgF 03 2 Seq",
    "DmgF 03 1 Seq",
    "DmgF 03 0 Seq",
    "DmgDownF03 0",
    "DmgDownF 02 2 Seq",
    "DmgDownF 02 0 Seq",
    "DmgDownF 01 2 Seq",
    "DmgDownF 01 0 Seq",
    "DmgDownB03 0",
    "DmgDown02 2 Seq",
    "DmgDown02 0 Seq",
    "DmgDown01 2 Seq",
    "DmgDown01 0 Seq",
    "DmgCatch 03 2 Seq",
    "DmgCatch 03 1 Seq",
    "DmgCatch 03 0 Seq",
    "DmgCatch 02 2 Seq",
    "DmgCatch 02 1 Seq",
    "DmgCatch 02 0 Seq",
    "DmgCatch 01 2 Seq",
    "DmgCatch 01 1 Seq",
    "DmgCatch 01 0 Seq",
    "DmgBlowF 01 1 Seq",
    "DmgBlowF 01 0 Seq",
    "DmgBlow01 1 Seq",
    "DmgBlow01 0 Seq",
    "DmgB02",
    "DmgB01",
    "Dmg03 2 Seq",
    "Dmg03 1 Seq",
    "Dmg03 0 Seq",
    "Die 01 2 Seq",
    "Die 01 1 Seq",
    "Die 01 0 Seq",
    "ChainWait 01 2 Seq",
    "ChainWait 01 1 Seq",
    "ChainWait 01 0 Seq",
    "ChainTatakauJ01 0",
    "ChainTatakau01 0",
    "ChainSPGuard 01 3 Seq",
    "ChainSPGuard 01 2 Seq",
    "ChainSPGuard 01 1 Seq",
    "ChainSPGuard 01 0 Seq",
    "ChainRangeAtk01 0",
    "ChainJump A03 0",
    "ChainJump A02 2 test",
    "ChainJump A02 1 test",
    "ChainJump A02 0 test",
    "ChainJump A02 0",
    "ChainJump A 01 2 Seq",
    "ChainJump A 01 1 Seq",
    "ChainJump A 01 0 Seq",
    "ChainGuard A01 0",
    "ChainGuard 01 2 Seq",
    "ChainGuard 01 1 Seq",
    "ChainGuard 01 0 Seq",
    "ChainDodge01 0",
    "ChainDodge A 02 3 Seq",
    "ChainDodge A 02 2 Seq",
    "ChainDodge A 01 3 Seq",
    "ChainDodge A 01 2 Seq",
    "ChainDodge A 01 0 Seq",
    "ChainCounter02 0",
    "ChainCounter A02 0",
    "ChainCounter A 01 3 Seq",
    "ChainCounter A 01 2 Seq",
    "ChainCounter A 01 1 Seq",
    "ChainCounter A 01 0 Seq",
    "ChainCharge01 0",
    "BurstChain Vision01",
    "BurstChain 02 07 01 0",
    "BurstChain 02 05 02 0",
    "BurstChain 02 04 02 0",
    "BurstChain 02 04 01 0",
    "BurstChain 02 03 02 0",
    "BurstChain 01 02 01 0",
    "BurstChain 00 02 02 0",
    "BurstChain 00 02 01 0",
    "AvoidStpR01",
    "AvoidStpL01",
    "AvoidStpF01",
    "AvoidStpB01",
    "AvoidJ02",
    "AvoidJ01",
    "AvoidJ 10 2 Seq",
    "AvoidJ 10 1 Seq",
    "AvoidJ 10 0 Seq",
    "Avoid02",
    "Avoid01 test",
    "Avoid01",
    "AtkLimit03 0",
    "AtkLimit02 0",
    "AtkLimit01 0",
    "AtkBurstJ07 0",
    "AtkBurstJ 10 2 Seq",
    "AtkBurstJ 10 1 Seq",
    "AtkBurstJ 10 0 Seq",
    "AtkBurstJ 08 2 Seq",
    "AtkBurstJ 08 1 Seq",
    "AtkBurstJ 08 0 Seq",
    "AtkBurst08 0",
    "AtkBurst06 0",
    "AtkBurst05 0",
    "AtkBurst04 0",
    "AtkBurst02 0",
    "AtkBurst 10 2 Seq",
    "AtkBurst 10 1 Seq",
    "AtkBurst 10 0 Seq",
    "AtkBurst 09 1 Seq",
    "AtkBurst 09 0 Seq",
    "AtkBurst 07 1 Seq",
    "AtkBurst 07 0 Seq",
    "AtkBurst 03 1 Seq",
    "AtkBurst 03 0 Seq",
    "AtkBurst 01 1 Seq",
    "AtkBurst 01 0 Seq",
    "AtkBlowAwayD03",
    "Abnormal 01 2 Seq",
    "Abnormal 01 1 Seq",
    "Abnormal 01 0 Seq",
    "Ability05 2 2 Seq",
    "Ability05 2 1 Seq",
    "Ability05 2 0 Seq",
    "Ability05 0",
    "Ability 06 2 Seq",
    "Ability 06 1 Seq",
    "Ability 06 0 Seq",
    "Ability 04 2 Seq",
    "Ability 04 1 Seq",
    "Ability 04 0 Seq",
    "Ability 03 2 Seq",
    "Ability 03 1 Seq",
    "Ability 03 0 Seq",
    "Ability 02 2 Seq",
    "Ability 02 1 Seq",
    "Ability 02 0 Seq",
    "Ability 01 2 Seq",
    "Ability 01 1 Seq",
    "Ability 01 0 Seq",
    "AAttack 01 1 Seq",
    "AAttack 01 0 Seq",   
    "Man 01 Enter Walk 02",
    "Man 01 Listen 01",
    "Man 01 Listen a01",
    "Man 01 Listen a02",
    "Man 01 Listen a03",
    "Man 01 Listen a04",
    "Man 01 ListenL 02",
    "Man 01 ListenR 01",
    "Man 01 ListenR 02",
    "Man 01 Talk A a04",
    "Man 01 Talk H a02",
    "Man 01 Talk H a06",
    "Man 01 Talk H a07",
    "Man 01 Talk H a08",
    "Man 01 Talk N a01",
    "Man 01 Talk N a02",
    "Man 01 Talk N a03",
    "Man 01 Talk N a04",
    "Man 01 Talk N a05",
    "Man 01 Talk N a06",
    "Man 01 Talk N a07",
    "Man 01 Talk N a08",
    "Man 01 Talk N a09",
    "Man 01 Talk N a10",
    "Man 01 Talk N a11",
    "Man 01 Talk N a12",
    "Man 01 Talk N a13",
    "Man 01 Talk N a14",
    "Man 01 Talk N a15",
    "Man 01 Talk N b01",
    "Man 01 Talk N b03",
    "Man 01 Talk N b04",
    "Man 01 Talk N b05",
    "Man 01 Talk N b06",
    "Man 01 Talk N b07",
    "Man 01 Talk N b08",
    "Man 01 Talk N b09",
    "Man 01 Talk N b10",
    "Man 01 Talk N b11",
    "Man 01 Talk N b12",
    "Man 01 Talk N b13",
    "Man 01 Talk N b14",
    "Man 02 Listen 01",
    "Man 02 Listen a01",
    "Man 02 Listen a02",
    "Man 02 Listen a03",
    "Man 02 ListenL 01",
    "Man 02 ListenR 01",
    "Man 02 Talk A a03",
    "Man 02 Talk H a05",
    "Man 02 Talk N a01",
    "Man 02 Talk N a02",
    "Man 02 Talk N a03",
    "Man 02 Talk N a04",
    "Man 02 Talk N a05",
    "Man 02 Talk N a06",
    "Man 02 Talk N a07",
    "Man 02 Talk N a08",
    "Man 02 Talk N a09",
    "Man 02 Talk N a10",
    "Man 02 Talk N a11",
    "Man 02 Talk N a13",
    "Man 02 Talk N a14",
    "Man 02 Talk N b01",
    "Man 02 Talk N b02",
    "Man 02 Talk N b03",
    "Man 02 Talk N b04",
    "Man 02 Talk N b05",
    "Man 02 Talk N b06",
    "Man 02 Talk N b07",
    "Man 02 Talk N b08",
    "Man 02 Talk N b09",
    "Man 02 Talk N b10",
    "Man 02 Talk N b11",
    "Man 02 Talk N b13",
    "Man 03 Listen 01",
    "Man 03 Listen a01",
    "Man 03 Listen a02",
    "Man 03 Listen a03",
    "Man 03 ListenL 01",
    "Man 03 ListenL 02",
    "Man 03 ListenR 01",
    "Man 03 ListenR 02",
    "Man 03 Talk A a05",
    "Man 03 Talk H a05",
    "Man 03 Talk N a01",
    "Man 03 Talk N a02",
    "Man 03 Talk N a03",
    "Man 03 Talk N a04",
    "Man 03 Talk N a05",
    "Man 03 Talk N a06",
    "Man 03 Talk N a07",
    "Man 03 Talk N a08",
    "Man 03 Talk N a09",
    "Man 03 Talk N a10",
    "Man 03 Talk N a11",
    "Man 03 Talk N a12",
    "Man 03 Talk N a13",
    "Man 03 Talk N a14",
    "Man 03 Talk N b01",
    "Man 03 Talk N b02",
    "Man 03 Talk N b03",
    "Man 03 Talk N b04",
    "Man 03 Talk N b05",
    "Man 03 Talk N b06",
    "Man 03 Talk N b07",
    "Man 03 Talk N b08",
    "Man 03 Talk N b09",
    "Man 03 Talk N b10",
    "Man 03 Talk N b11",
    "Man 03 Talk N b12",
    "Man 03 Talk N b13",
    "Man 03 Talk N b14",
    "Man 03 Talk N b15",
    "Man BIdle01 0",
    "Man BIdle01 1",
    "Man Idle01 1",
    "Man Idle01to02",
    "Man Idle02 1",
    "Man Idle02to01",
    "Man Idle03 1",
    "Man Idle03to01"
    ]},
    {nombre: "Big Rumble Boxing", data:[
        "Pow U DodgeHook 05",
    "Pow U ChargeHook 01 MinCharge",
    "Pow U ChargeHook 01 MaxCharge",
    "Pow U ChargeHook 01 Charging",
    "Pow N Straight",
    "Pow N Flurry 01 FinalHit",
    "Pow N Flurry 01",
    "Pow N ChargeUppercut 01 MinCharge",
    "Pow N ChargeUppercut 01 MaxCharge",
    "Pow N ChargeUppercut 01 Charging",
    "Pow F LungeUppercut 01",
    "Pow F LungeOverhand 02",
    "Pow F 2HitLunge 02",
    "Pow D UnstoppableHook 01",
    "Pow D DodgeHook 05",
    "Pow D ChargeHook 01 MinCharge",
    "Pow D ChargeHook 01 MaxCharge",
    "Pow D ChargeHook 01 Charging",
    "Pow B UnblockableStraight 01",
    "Pow B DefChargeStrike NoCharge",
    "Pow B DefChargeStrike FullCharge",
    "Pow B DefChargeStrike Charging",
    "Pow B DashBackStraight 03",
    "Grab 02 Target",
    "Grab 02 Source",
    "Grab 02 Miss",
    "Finish Swarm 06 Taunt",
    "Finish Swarm 06 OnHit GolpeRec",
    "Finish Swarm 06 OnHit Golpe",
    "Finish Swarm 05 Taunt",
    "Finish Swarm 05 OnHit GolpeRec",
    "Finish Swarm 05 OnHit Golpe",
    "Finish Swarm 04 Taunt",
    "Finish Swarm 04 OnHit GolpeRec",
    "Finish Swarm 04 OnHit Golpe",
    "Finish Swarm 03 Taunt",
    "Finish Swarm 03 OnHit GolpeRec",
    "Finish Swarm 03 OnHit Golpe",
    "Finish Swarm 02 Taunt",
    "Finish Swarm 02 OnHit GolpeRec",
    "Finish Swarm 02 OnHit Golpe",
    "Finish Swarm 01 Taunt",
    "Finish Swarm 01 OnHit GolpeRec",
    "Finish Swarm 01 OnHit Golpe",
    "Finish Stub 02 HIT",
    "Finish Stub 02",
    "Finish Slug 07 Taunt",
    "Finish Slug 07 OnHit GolpeRec",
    "Finish Slug 07 OnHit Golpe",
    "Finish Slug 06 Taunt",
    "Finish Slug 06 OnHit GolpeRec",
    "Finish Slug 06 OnHit Golpe",
    "Finish Slug 05 Taunt",
    "Finish Slug 05 OnHit GolpeRec",
    "Finish Slug 05 OnHit Golpe",
    "Finish Slug 04 Taunt",
    "Finish Slug 04 OnHit GolpeRec",
    "Finish Slug 04 OnHit Golpe",
    "Finish Slug 03 Taunt",
    "Finish Slug 03 OnHit GolpeRec",
    "Finish Slug 03 OnHit Golpe",
    "Finish Slug 02 Taunt",
    "Finish Slug 02 OnHit GolpeRec",
    "Finish Slug 02 OnHit Golpe",
    "Finish Slug 01 StartUp",
    "Finish Slug 01 OnHit GolpeRec",
    "Finish Slug 01 OnHit Golpe",
    "Finish Gen 07 Taunt",
    "Finish Gen 07 OnHit GolpeRec",
    "Finish Gen 07 OnHit Golpe",
    "Finish Gen 06 Taunt",
    "Finish Gen 06 OnHit GolpeRec",
    "Finish Gen 06 OnHit Golpe",
    "Finish Gen 05 Taunt",
    "Finish Gen 05 OnHit GolpeRec",
    "Finish Gen 05 OnHit Golpe",
    "Finish Gen 04 Taunt",
    "Finish Gen 04 OnHit GolpeRec",
    "Finish Gen 04 OnHit Golpe",
    "Finish Gen 03 Taunt",
    "Finish Gen 03 OnHit GolpeRec",
    "Finish Gen 03 OnHit Golpe",
    "Finish Gen 02 Taunt",
    "Finish Gen 02 OnHit GolpeRec",
    "Finish Gen 02 OnHit Golpe",
    "Finish Gen 01 Taunt",
    "Finish Gen 01 OnHit Def",
    "Finish Gen 01 OnHit",
    "ATK RUpper Low S 01",
    "ATK RUpper Low M 01",
    "ATK RUpper Low L 01",
    "ATK RUpper High S 01",
    "ATK RUpper High M 01",
    "ATK RUpper High L 01",
    "ATK ROverhand S 01",
    "ATK ROverhand M 01",
    "ATK ROverhand L 01",
    "ATK RHook Low S 01",
    "ATK RHook Low M 01",
    "ATK RHook Low L 01",
    "ATK RHook High S 01",
    "ATK RHook High M 01",
    "ATK RHook High L 01",
    "ATK LUpper Low S 01",
    "ATK LUpper Low M 01",
    "ATK LUpper Low L 01",
    "ATK LUpper High S 01",
    "ATK LUpper High M 01",
    "ATK LUpper High L 01",
    "ATK Lunge Jab Body",
    "ATK LOverhand S 01",
    "ATK LOverhand M 01",
    "ATK LOverhand L 01",
    "ATK LHook Low S 01",
    "ATK LHook Low M 01",
    "ATK LHook Low L 01",
    "ATK LHook High S 01",
    "ATK LHook High M 01",
    "ATK LHook High L 01",
    "ATK Jab Low S 01",
    "ATK Jab Low M 01",
    "ATK Jab Low L 01",
    "ATK Jab High S 01",
    "ATK Jab High M 01",
    "ATK Jab High L 01",
    "ATK Cross Low S 01",
    "ATK Cross Low M 01",
    "ATK Cross Low L 01",
    "ATK Cross High S 01",
    "ATK Cross High M 01",
    "ATK Cross High L 01",
    "ATK Cross Body",
    "Anim Atk Lunge Jab L Head 01"
    ]},
    {nombre: "Life is Strange", data:[
        " SitBench01 Base LM",
        " SitBench01 touchHead LM",
        "01 couple A Loop LM",
        "01 couple B Loop LM",
        "Alarm  LM",
        "AndDavid LM",
        "AnotherReality Logan LM",
        "AskLight left LM",
        "AskMusic v02 LM",
        "AskPhoto LM",
        "AskWater LM",
        "Barman LM",
        "Bus Driver LM",
        "Bus LM",
        "BusDriver LM",
        "BusRide BusDriver LM",
        "BusRide Curve BusDriver LM",
        "BusRide Curve Evan LM",
        "BusRide Curve Zachary LM",
        "BusRide Driver LM",
        "BusRide Evan LM",
        "BusRide SeeWhales BusDriver LM",
        "BusRide Zachary LM",
        "Button Male LM",
        "Choice Denounce  LM",
        "Choice SitLoop LM",
        "Choice TakeGunFast LM",
        "ChoiceDavid LM",
        "ChoiceDenounceDavidLoop LM",
        "ChoiceHelpDavid LM",
        "ChoiceLie LM",
        "ChoiceTruth Part1 LM",
        "ChoiceTruth Part1LM",
        "ChoiceTruth Part2 LM",
        "Choise Walk Stand LM",
        "CHouseFront DoorKnocking LM",
        "ClosedLocker Evan LM",
        "ClosedLocker EvanDiscuss Loop LM",
        "Conflict ChoiceNoShoot LM",
        "Conflict ChoiceShoot LM",
        "Conflict Start Walk Talk LM",
        "Couple DiscussFish01 LM",
        "Couple DiscussFish01 Walk LM",
        "Couple DiscussLove A Loop LM",
        "Couple Fight C LM",
        "Couple Fight C Loop LM",
        "Couple FootPlay A Loop LM",
        "couple FootPlay B Loop LM",
        "Couple01 B LM",
        "Couple02 B LM",
        "Couple1 afterBelt Male LM",
        "Couple1 idleLoop Male LM",
        "Couple2 Sit afterBelt Male LM",
        "Couple2 Sit belt Male LM",
        "Couple2 Sit idleLoop Male LM",
        "CoupleDiscuss Zachary LM",
        "CoupleDiscuss02 Walk LM",
        "CupBoard01 afterBelt Male LM",
        "CupBoard01 belt Male LM",
        "CupBoard01 idleLoop Male LM",
        "Dana Trevor LM",
        "DanaModel CameraStop Hayden LM",
        "DanaModel React Hayden LM",
        "DanaModel WaitLoop Hayden LM",
        "DanaTrevorLoop Trevor LM",
        "Dancing01 Male01 LM",
        "Dancing02 Male01 LM",
        "DavidCheckLoop LM",
        "DavidCheckLoop Reverse LM",
        "DavidCheckLoop Reverseson LM",
        "DavidFurious ChoiceNotHidden LM",
        "DavidFurious DavidDesk LM",
        "DavidFurious Intervene LM",
        "DavidFurious Slap LM",
        "DavidFury David",
        "DavidHit LM",
        "DavidHome LM",
        "DavidLeaving LM",
        "DavidShouts David",
        "DavidUntie LM",
        "DavidvsNathan LM",
        "DeadV3 LM",
        "DifficultFocus B LM",
        "DiscussionLoop LM",
        "DiscussionLoop02 LM",
        "DJAudioCut DJ LM",
        "DJLoop DJ LM",
        "DogReaction 02 LM",
        "Drunk LoopDoor  LM",
        "Drunk LoopSit  LM",
        "Drunk Move  LM",
        "Drunk Part2  LM",
        "DuoHelp01 Loop LM",
        "DuoHelp01 WalkPath LM",
        "DuoHelp02 Loop LM",
        "DuoHelp02 WalkPath LM",
        "Eating  LM",
        "Eating B LM",
        "End  LM",
        "EntranceGuardLoop LM",
        "EpisodeEndson LM",
        "Evan Loop LM",
        "EvanDieHeadshot v02 Evan LM",
        "EvanHelp LoopBis Evan LM",
        "EvanHelp v01 Evan LM",
        "EvanHelp v02 Evan LM",
        "Extraction  LM",
        "Extraction LM",
        "Fall BoyL LM",
        "FellLoop BoyL LM",
        "FightP1 CameraOK LM",
        "FightP1 CameraOKson LM",
        "FightP1 Default LM",
        "FightP1 Defaultson LM",
        "FightP1 MusicOn LM",
        "FightP1 MusicOnson LM",
        "FightP1 TrolleyOK LM",
        "FightP1 TrolleyOKson LM",
        "FightP1 WarnOK LM",
        "FightP1 WarnOKson LM",
        "FightP1 WarnTooEarlyson LM",
        "FightP2 Default LM",
        "FightP2 Defaultson LM",
        "FightP2 GunNoOK LM",
        "FightP2 GunNoOKson LM",
        "FightP2 GunOk LM",
        "FightP2 GunOkson LM",
        "FightP2 LightOk LM",
        "FightP2 LightOkson LM",
        "FightP2 Table LM",
        "FightP2 Tableson LM",
        "FightP2 WarnNok LM",
        "FightP2 WarnNokson LM",
        "FireAlarm Interact01 LM",
        "FishermanDie deadLoop LM",
        "FishermanDie Electro LM",
        "FishermanDie idelLoop LM",
        "FishermanHelp Sit LM",
        "FishermanJukebox LM",
        "FishermanLoop LM",
        "FloorWalk idleLoop LM",
        "FloorWalk WalkPath LM",
        "Frank close door LM",
        "Frank Give back Gun LM",
        "Frank LoopListen LM",
        "Frank LoopTalk LM",
        "FrankBeans LM",
        "FrankBeer LM",
        "FrankEating LM",
        "FrankHurt Sit LM",
        "FrankKeys Sit LM",
        "FrankRachel Sit LM",
        "FrankSeeGirls Sit LM",
        "FrankSleeping LM",
        "Garage DavidWorking LM",
        "Garage DavidWorkingLaptop LM",
        "Garage Puzzle LM",
        "GEN Stand Wait Loop LM",
        "GEN WalkFast Loop LM",
        "GEN WalkFast Turn90R LM",
        "GEN WalkSlow Loop LM",
        "GEN WalkSlow Turn90L LM",
        "GEN WalkSlow Turn90R LM",
        "GEN WalkStairDown Loop LM",
        "GivePaper  LM",
        "GivePhoto LM",
        "Group01 B LM",
        "GuardAlert Girlslocker Walk LM",
        "GuardAlert Walk 03 LM",
        "Hayden Sit LM",
        "Hayden Sit Loop LM",
        "HaydenLoop Hayden LM",
        "Hurt Loop Zachary LM",
        "Insertion Evan LM",
        "Insertion Evan Loop LM",
        "Insertion Samuel Loop LM",
        "Insertion Sit  LM",
        "Insertion Stand LM",
        "Insertion2 JeffWorking LM",
        "Insertion2 JeffWorking Loop LM",
        "Insertion2 Sit LM",
        "InsertionPart1 LM",
        "InsertionPart2 LM",
        "InsertionPart3 LM",
        "InsertionPartVic LM",
        "Insertionson LM",
        "InterruptIGE Logan LM",
        "InterruptRTC LM",
        "Intervene  Idle LM",
        "Intervene  LM",
        "Intro Sit LM",
        "IntroLoop BoyL LM",
        "IpadStress afterBelt Male LM",
        "IpadStress belt Male LM",
        "IpadStress idleLoop Male LM",
        "JanitorClean Loop Samuel LM",
        "JanitorPaint Intro Samuel LM",
        "JanitorPaint Loop 01 Samuel LM",
        "JanitorPaint Loop Samuel LM",
        "Jeff IdleWait01 LM",
        "Jeff LoopWait LM",
        "Jeff PhoneLoop LM",
        "Jeff Speak01 LM",
        "Jeff Speak02 LM",
        "Jeff Speak03 CrossArms LM",
        "Jeff TakePhone LM",
        "JeffArriveReaction BoyL LM",
        "JeffArriveReaction DJ LM",
        "JeffArriveReaction Drunk BoyL LM",
        "JeffArriveReaction End BoyL LM",
        "JeffersonStopsMax LM",
        "JeffersonTalks LM",
        "JeffGivingLesson LM",
        "JeffKate Argue LM",
        "JeffKate LoopStart LM",
        "JeffVicTalking Part2 LM",
        "JeffWaitingAnswerLoop LM",
        "JeffWalking LM",
        "Journalist B LM",
        "Journalist Interview B LM",
        "Journalist LoopCall B LM",
        "Journalist LoopWait B LM",
        "JoyceLoop OldMan LM",
        "JulietZac Zac LM",
        "Junkyard Endson LM",
        "Kate Intervene LM",
        "Kate LM",
        "Kate TakePhoto LM",
        "KeysOnMax LM",
        "KeysOut01 LM",
        "KeysOut03 LM",
        "Looking01 B LM",
        "Looking02 B LM",
        "Looking03 LM",
        "Looking04 LM",
        "LookingWalk03 LM",
        "LookingWalk04 LM",
        "Loop  LM",
        "Loop LM",
        "Loop Stand LM",
        "Loop Zac LM",
        "Loop01 B LM",
        "Loop02 B LM",
        "LoopLocker Evan LM",
        "Loopson LM",
        "LoopTalkingson LM",
        "MainEntrance Guard LM",
        "MaxAnswers LM",
        "MaxAwake01 LM",
        "MaxPickUpPhone LM",
        "MeetTrevor Trevor LM",
        "MenToiletPissDrunk BoyL LM",
        "MenToiletSquat BoyL LM",
        "Model CameraLoopson LM",
        "Money LM",
        "MopBroom01 Loop Samuel LM",
        "NathanAnd Nathan LM",
        "NoMoney LM",
        "OldGuyLoop LM",
        "OldManLoop OldMan LM",
        "PartJoyce Cop LM",
        "PartJoyce Trevor LM",
        "PartJoyce Trucker01 LM",
        "PartJoyce Trucker02 LM",
        "PhotoLook B LM",
        "RageBattle dog LM",
        "RageBattle LM",
        "RageDog LM",
        "RageGun LM",
        "RageGunV2 LM",
        "RageKnife LM",
        "RageNoGun LM",
        "Recovery Choice LM",
        "Run CampusPark MaxChoose LM",
        "Run Jog Loop LM",
        "Run Jog Turn90R LM",
        "Run Turn90L LM",
        "RVDoor LM",
        "Sign LM",
        "Sign Sit Walk LM",
        "Signson Stand LM",
        "Sit Announcement  LM",
        "Sit Base LM",
        "Sit Bird LM",
        "Sit Breathe LM",
        "Sit Choice Loop LM",
        "Sit Choice PcLoop LM",
        "Sit Cop Donut Loop LM",
        "Sit Drunk ShortReaction  LM",
        "Sit Explain01 T LM",
        "Sit LookAway T LM",
        "Sit LoopAfter  LM",
        "Sit Outro LM",
        "Sit Speak T LM",
        "Sit Speak01 Loop01 LM",
        "Sit Table LM",
        "Sit Wait01 LM",
        "Sit Wait02 LM",
        "Sit WaitOnFloor Loop LM",
        "SitCameraLoop Hayden LM",
        "SitChair01 Agreed LM",
        "SitChair01 Base LM",
        "SitChair01 Explain01 T LM",
        "SitChair01 Itchy LM",
        "SitChair01 Septic T LM",
        "SitChair01 uncomfortable T LM",
        "SitChair01 Wait01 LM",
        "SitChair02 Base LM",
        "SitChair02 Explain01 T LM",
        "SitChair02 Wait01 LM",
        "SitGround02 Base LM",
        "SitGround02 Breathe LM",
        "SitGround02 Breathe T LM",
        "SitGround02 LookAway LM",
        "SitGround02 Speak T LM",
        "SitGround02 Wait01 LM",
        "Sitting01 B LM",
        "Sleep afterBelt Male LM",
        "Sleeping Warning LM",
        "sonTalk LM",
        "Speak01 Loop02 LM",
        "Stand Choice Protect  LM",
        "Stand FishPetition Loop 01 LM",
        "Stand FishPetition Loop 03 LM",
        "Stand FishPetition Loop LM",
        "Stand Insertion  LM",
        "Stand LM",
        "Stand MopBroom Loop LM",
        "Stand PaperRead Loop LM",
        "Stand Phone Loop LM",
        "Stand WaitStrict01 Base LM",
        "Stand WaitStrict01 Idle01 LM",
        "Stand WaitStrict01 Idle02 LM",
        "Stand WaitStrict02 Base LM",
        "Stand Walk BouncerSTOP LM",
        "Stand Walk Listen LM",
        "Stand Walk Talk Begin  LM",
        "Stand01 Agreed LM",
        "Stand01 Base LM",
        "Stand01 CrossArm LM",
        "Stand01 Explain01 T LM",
        "Stand01 Explain02 T LM",
        "Stand01 Explain03 T LM",
        "Stand01 Explain04 T LM",
        "Stand01 Explain05 T LM",
        "Stand01 TouchNeck LM",
        "Stand01 TouchNose LM",
        "Stand01 TurnHead LM",
        "Stand02 Agreed LM",
        "Stand02 Base LM",
        "Stand02 Explain01 T LM",
        "Stand02 Explain02 T LM",
        "Stand02 Septic T LM",
        "Stand02 Think LM",
        "Stand02 Wait01 LM",
        "StandB LM",
        "StandDavid LM",
        "StandWalk idleLoop LM",
        "StandWalk WalkPath LM",
        "Talk Walk BellRing LM",
        "Talks  LM",
        "ThrowBall Loop Zachary LM",
        "ThrowBall Zachary LM",
        "TiedOnFloor Loopson LM",
        "TrevorGetout Trevor LM",
        "TrevorJustin Loop Trevor LM",
        "Trio ildeLoop LM",
        "Trio WalkPath LM",
        "TruckerHelp Helped Trucker LM",
        "TruckerHelp idleLoop Trucker LM",
        "Truckers  Trucker01 LM",
        "Truckers LaughAtMax Trucker02 LM",
        "Truckers Loop Trucker01 LM",
        "Truckers Loop Trucker02 LM",
        "VictoriaBitch Samuel LM",
        "VictoriaHurt Samuel LM",
        "VictoriaJoke LM",
        "VIP DrunkCrew  LM",
        "VIP DrunkCrew Loop LM",
        "VIPKeeper Bouncer LM",
        "Wait01 LM",
        "Wait02 LM",
        "WaitingBus01 LoopTicket LM",
        "WaitLoop Fisherman LM",
        "WaitLoop Samuel LM",
        "Walk Stand Anger LM",
        "Walk Success LM",
        "Walk Talk BeginLesson LM",
        "WalkAlone Part01 LM",
        "WalkAlone Part01 Loop LM",
        "WalkAlone Part02 LM",
        "WalkAlone Part02 Loop LM",
        "WalkAlone Part03 LM",
        "WalkAlone Part03 Loop LM",
        "Walking Male LM",
        "WalkLeave LM",
        "WalkLoop LM",
        "WalkRelax Loop LM",
        "WalkRelax Loop02 LM",
        "WalkSlow LM",
        "WalkSlow PushDoor LM",
        "WalkSlow Turn90R LM",
        "WalkStair  LM",
        "WalkToStop LM",
        "Warn BoyL LM",
        "WarnedLoop BoyL LM",
        "WilliamBeepNoKeys LM",
        "WilliamCooking Loop LM",
        "WilliamCooking William LM",
        "WilliamNeedCarKeys End LM",
        "WilliamNeedCarKeys HomePhone LM",
        "WilliamNeedCarKeys MobilePhone LM",
        "WilliamTakeBus LM",
        "WilliamWeirdKeys LM",
        "Window Sit Belt Male LM",
        "Window Sit idleLoop Male LM",
        "Window Sit Male LM",
        "WritesOnSlate Loop LM"
    ]},
  ];
  
  const arraySubCategoria = [
    { nombre: "Head", data: ["Cabeza", "Craneo", "Head"] },
    { nombre: "Talk", data: ["Talk", "Chat", "Say", "Converse", "Dialogue", "Conversando", "Hablar"] },
    { nombre: "Fly", data: ["Vuelo", "Aire", "Fly", "Flying","Air","Air", "Jump", "Aerial", "Fly", "Float", "Aire", "Salto", "Aéreo", "Volar"] },
    { nombre: "Idle", data: ["Idle", "Quieto", "Reposo", "Rest", "Wait", "Still", "Standby", "Pause","Inactivo", "Reposo", "Quieto"] },
    { nombre: "Weapon", data: ["Weapon", "Arma", "Pistola", "Escopeta","Metralleta","Cuchillo","Rifle"] },
    { nombre: "Interact", data: ["Interact", "Objeto", "Arma", "Escopeta","Metralleta","Cuchillo","Pistola","Use", "Activate", "Grab", "Press", "Manipulate","Interactuar", "Usar", "Tocar", "Activar","Bate"] },
    { nombre: "Hit", data: ["Golpear", "ATK", "Finish", "Pow", "Attack","Patada","Hit", "Strike", "Impact", "Blow", "Smash", "Punch","Golpe", "Impacto", "Puñetazo", "Strike", "Punch", "Smash", "Impact"]},
    { nombre: "Walk", data: ["Walk", "Caminar", "Caminata", "Andar", "Pasear", "Stroll", "Pace", "Step"] },
    { nombre: "Run", data: ["Run", "Sprint", "Dash", "Race", "Hustle","Sprint", "Jog", "Dash", "Rush" , "Correr", "Trotar", "Apresurarse"] },
    { nombre: "Recovery", data: ["Recovery", "Heal", "Regain", "Restore", "GetUp", "StandUp", "Recuperación", "Sanar", "Levantarse","Heal", "Regain", "GetUp"] },
    { nombre: "Stun", data: ["Stun", "Daze", "Knockback", "Freeze", "Dizzy", "Paralyze", "Aturdir", "Tambalear", "Desorientar","Dazed", "Knockback", "Stagger"] },
    { nombre: "Combat", data: ["Combat", "Fight", "Battle", "Melee", "Brawl", "Engage", "Combate", "Pelea","Fight", "Battle", "Engage","Combate", "Pelea", "Lucha"] },
    { nombre: "Death", data: ["Death", "Die", "Dead", "Kill", "Finish", "Downed", "Muerte", "Caer", "Fallecer", "Die", "Fall", "Collapse", "Perish"] },
    { nombre: "Combos", data: ["Combos", "Chains", "Sequences", "Attacks", "Move Set","Combo", "Chain"] },
    { nombre: "Shoot", data: ["Shoot", "Fire", "Blast", "Gun", "Aim", "Disparar", "Blast", "Gunfire"] },
    { nombre: "Climb", data: ["Climb", "Scale", "Ascend", "Mount", "CrawlUp", "Escalar", "Trepar", "Subir"] },
    { nombre: "GetShot", data: ["GetShot", "TakeHit", "Damaged", "HitReaction", "ImpactReceived", "Recibir Disparo", "Ser golpeado", "Herido", "Hit", "TakeDamage", "Injured", "Impact"] },
    { nombre: "Emotes", data: ["Expressions", "Gestures", "Reactions","Gestos", "Emociones", "Reacciones"] },
    { nombre: "Dance", data: ["Dance", "Move", "Groove", "Boogie", "Bailar", "Moverse", "Danza", "Dancing", "dnce"] },
    { nombre: "Launch", data: ["Lanzar", "Impulsar", "Arrojar","Throw", "Propel", "Toss"] },
    { nombre: "Loop", data: ["Bucle", "Ciclo", "Repetición", "Cycle", "Repeat", "Looping", "Loop"] },
    { nombre: "Zombie", data: ["Zombie", "Zombi", "Muertos"] },
    { nombre: "Vehiculo", data: ["Accidente", "Carro", "Atropello", "Bus", "Driver", "Taxi"] },
    { nombre: "Land", data: ["Land", "Suelo", "Piso", "Tierra"] },
    { nombre: "Listen", data: ["Listen", "Escuchar", "Oir", "Oido", "Tune in", "Hea", "Pay attention"] }
  ];
