// --- Datos (sin cambios) ---
    const modelosTipo = ["San Andreas"];
        //const arraySex = ["Masculino", "Femenino", "N/A"];
        //Especial  Pandilla    Zombie  Peaton  Oficio  Policia 
    const modelos = [
    {nombre:"army gtasa", tipo:"San Andreas", categoria:"Zombie, Policia", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"BFORI gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"BFOST gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"BFYBE gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"BFYBU gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"BFYPRO gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"BFYRI gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"BFYST gtasa", tipo:"San Andreas", categoria:"Peaton", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"BIKERA gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"BIKERB gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"BMOBAR gtasa", tipo:"San Andreas", categoria:"Zombie, Oficio", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"BMOCD gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"BMOCHIL gtasa", tipo:"San Andreas", categoria:"Zombie, Oficio", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"BMORI gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"BMOSEC gtasa", tipo:"San Andreas", categoria:"Zombie, Oficio", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"BMOST gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"BMOTR1 gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"BMYAP gtasa", tipo:"San Andreas", categoria:"Oficio", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"BMYBAR gtasa", tipo:"San Andreas", categoria:"Oficio", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"BMYBE gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"BMYBOUN gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"BMYBU gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"BMYCG gtasa", tipo:"San Andreas", categoria:"Zombie, Oficio", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"BMYCON gtasa", tipo:"San Andreas", categoria:"Zombie, Oficio", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"BMYCR gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"BMYDJ gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"BMYDRUG gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"BMYMIB gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"BMYMOUN gtasa", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"BMYPIMP gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"BMYPOL1 gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"BMYPOL2 gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"BMYRI gtasa", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"BMYST gtasa", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"BMYTATT gtasa", tipo:"San Andreas", categoria:"Oficio", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"COPGRL3 gtasa", tipo:"San Andreas", categoria:"Peaton", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"CROGRL3 gtasa", tipo:"San Andreas", categoria:"Oficio", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"csher gtasa", tipo:"San Andreas", categoria:"Zombie, Policia", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"CWFOFR gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"CWFOHB gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"CWFYFR1 gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"CWFYFR2 gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"CWFYHB gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"CWMOFR gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"CWMOHB1 gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"CWMOHB2 gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"CWMYFR gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"CWMYHB1 gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"CWMYHB2 gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"DNB1 gtasa", tipo:"San Andreas", categoria:"Zombie, Pandilla", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"DNB2 gtasa", tipo:"San Andreas", categoria:"Zombie, Pandilla", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"DNB3 gtasa", tipo:"San Andreas", categoria:"Zombie, Pandilla", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"DNFOLC1 gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"DNFOLC2 gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"DNFYLC gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"DNMOLC1 gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"DNMOLC2 gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"DNMYLC gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"dsher gtasa", tipo:"San Andreas", categoria:"Zombie, Policia", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"DWFOLC gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"DWFYLC1 gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"DWFYLC2 gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"DWMOLC1 gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"DWMOLC2 gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"DWMYLC1 gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"DWMYLC2 gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"fbi gtasa", tipo:"San Andreas", categoria:"Zombie, Policia", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"GANGRL3 gtasa", tipo:"San Andreas", categoria:"Especial", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"GUNGRL3 gtasa", tipo:"San Andreas", categoria:"Peaton", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"HECK1 gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"HECK2 gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"HFORI gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"HFOST gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"HFYBE gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"HFYPRO gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"HFYRI gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"HFYST gtasa", tipo:"San Andreas", categoria:"Peaton", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"HMOGAR gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"HMORI gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"HMOST gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"HMYBE gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"HMYCM gtasa", tipo:"San Andreas", categoria:"Zombie, Oficio", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"HMYCR gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"HMYDRUG gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"HMYRI gtasa", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"HMYST gtasa", tipo:"San Andreas", categoria:"Zombie, Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"laemt1 gtasa", tipo:"San Andreas", categoria:"Oficio", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"lafd1 gtasa", tipo:"San Andreas", categoria:"Zombie, Oficio", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"lapd1 gtasa", tipo:"San Andreas", categoria:"Zombie, Policia", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"lapdm1 gtasa", tipo:"San Andreas", categoria:"Zombie, Policia", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"LSV1 gtasa", tipo:"San Andreas", categoria:"Zombie, Pandilla", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"LSV2 gtasa", tipo:"San Andreas", categoria:"Zombie, Pandilla", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"LSV3 gtasa", tipo:"San Andreas", categoria:"Zombie, Pandilla", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"lvemt1 gtasa", tipo:"San Andreas", categoria:"Oficio", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"lvfd1 gtasa", tipo:"San Andreas", categoria:"Oficio, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"lvpd1 gtasa", tipo:"San Andreas", categoria:"Policia, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"MAFBOSS gtasa", tipo:"San Andreas", categoria:"Pandilla", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"MAFFA gtasa", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"MAFFB gtasa", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"MECGRL3 gtasa", tipo:"San Andreas", categoria:"Peaton", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"NURGRL3 gtasa", tipo:"San Andreas", categoria:"Peaton", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"OFORI gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"OFOST gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"OFYRI gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"OFYST gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"OMOBOAT gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"OMOKUNG gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"OMONOOD gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"OMORI gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"OMOST gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"OMYKARA gtasa", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"OMYRI gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"OMYST gtasa", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SBFORI gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"SBFOST gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"SBFYPRO gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"SBFYRI gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"SBFYST gtasa", tipo:"San Andreas", categoria:"Peaton", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"SBFYSTR gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"SBMOCD gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SBMORI gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SBMOST gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SBMOTR2 gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SBMYCR gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SBMYRI gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SBMYST gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SBMYTR3 gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"sfemt1 gtasa", tipo:"San Andreas", categoria:"Oficio", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"sffd1 gtasa", tipo:"San Andreas", categoria:"Oficio, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"sfpd1 gtasa", tipo:"San Andreas", categoria:"Policia, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SFR1 gtasa", tipo:"San Andreas", categoria:"Pandilla", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SFR2 gtasa", tipo:"San Andreas", categoria:"Pandilla", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SFR3 gtasa", tipo:"San Andreas", categoria:"Pandilla", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SFYPRO gtasa", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"SHFYPRO gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"SHMYCR gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SMYST gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SMYST2 gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SOFORI gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"SOFOST gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"SOFYBU gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"SOFYRI gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"SOFYST gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"SOMOBU gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SOMORI gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SOMOST gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SOMYBU gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SOMYRI gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SOMYST gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"swat gtasa", tipo:"San Andreas", categoria:"Policia, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SWFOPRO gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"SWFORI gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"SWFOST gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"SWFYRI gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"SWFYST gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"SWFYSTR gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"SWMOCD gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SWMORI gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SWMOST gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SWMOTR1 gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"SWMOTR2 gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SWMOTR3 gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SWMOTR4 gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SWMOTR5 gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SWMYCR gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SWMYHP1 gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SWMYHP2 gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SWMYRI gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"SWMYST gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"TRIADA gtasa", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"TRIADB gtasa", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"TRIBOSS gtasa", tipo:"San Andreas", categoria:"Pandilla", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"VBFYCRP gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"VBFYPRO gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"VBFYST2 gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"VBMOCD gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"VBMYBOX gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"VBMYCR gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"VBMYELV gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"VHFYPRO gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"VHFYST3 gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"VHMYCR gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"VHMYELV gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"VIMYELV gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"VLA1 gtasa", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"VLA2 gtasa", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"VLA3 gtasa", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"VMAFF1 gtasa", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"VMAFF2 gtasa", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"VMAFF3 gtasa", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"VMAFF4 gtasa", tipo:"San Andreas", categoria:"Pandilla, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"VWFYCRP gtasa", tipo:"San Andreas", categoria:"Peaton", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"VWFYPRO gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"VWFYST1 gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"VWFYWA2 gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"VWFYWAI gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"VWMOTR1 gtasa", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"VWMOTR2 gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"VWMYBJD gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"VWMYBOX gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"VWMYCD gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"VWMYCR gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WBDYG1 gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WBDYG2 gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WFORI gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"WFOST gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"WFYBE gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"WFYBU gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"WFYBURG gtasa", tipo:"San Andreas", categoria:"Oficio, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"WFYCLOT gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"WFYCRK gtasa", tipo:"San Andreas", categoria:"Oficio", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"WFYLG gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"WFYPRO gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"WFYRI gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"WFYRO gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"WFYSEX gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"WFYST gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"WFYSTEW gtasa", tipo:"San Andreas", categoria:"Peaton", sexo:"Femenino", rig:"ARPFortnite"},
    {nombre:"WMOICE gtasa", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMOMIB gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMOPJ gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMOPREA gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMORI gtasa", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMOSCI gtasa", tipo:"San Andreas", categoria:"Oficio, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMOST gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMOTR1 gtasa", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMYAMMO gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMYBAR gtasa", tipo:"San Andreas", categoria:"Oficio, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMYBE gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMYBELL gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMYBMX gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMYBOUN gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMYBP gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMYBU gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMYCD1 gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMYCH gtasa", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMYCLOT gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMYCON gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMYCONB gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMYCR gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMYDRUG gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMYGOL1 gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMYGOL2 gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMYJG gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMYKARA gtasa", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMYLG gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMYMECH gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMYMOUN gtasa", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMYPIZZ gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMYPLT gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMYRI gtasa", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMYRO gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMYSGRD gtasa", tipo:"San Andreas", categoria:"Policia, Zombie", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMYST gtasa", tipo:"San Andreas", categoria:"Peaton", sexo:"Masculino", rig:"ARPFortnite"},
    {nombre:"WMYVA gtasa", tipo:"San Andreas", categoria:"Peaton, Zombie", sexo:"Masculino", rig:"ARPFortnite"}
];
        /*for (let i = 1; i <= 50; i++) {
            let tipo, sexoDeterminado, categoriaEjemplo;
            const tipoIndex = i % modelosTipo.length;
            tipo = modelosTipo[tipoIndex];
            if (i % 3 === 0) sexoDeterminado = "N/A";
            else if (i % 2 === 0) sexoDeterminado = "Masculino";
            else sexoDeterminado = "Femenino";
            const catsBase = ["Aventura", "Acción", "Estrategia", "Puzzle", "Deporte", "Construcción", "Misterio", "Principal", "Secundario", "Jugador"];
            if (i % 4 === 0) categoriaEjemplo = `${catsBase[i%catsBase.length]}, ${catsBase[(i+1)%catsBase.length]}`;
            else if (i % 4 === 1) categoriaEjemplo = catsBase[i%catsBase.length];
            else if (i % 4 === 2) categoriaEjemplo = `${catsBase[i%catsBase.length]}, ${catsBase[(i+2)%catsBase.length]}, ${catsBase[(i+3)%catsBase.length]}`;
            else categoriaEjemplo = "General";
            modelos.push({ nombre: `Personaje${i}`, tipo: tipo, categoria: categoriaEjemplo, sexo: sexoDeterminado, rig: `RigDemo${i % 3}` });
        }*/
