const arrayTipos = ["Tierra", "Aire", "Mar"];
const arrayCategorias = [
    { categoria: "Autos compactos y de 2 puertas", tipo: "Tierra" },
    { categoria: "Autos de carreras callejeras", tipo: "Tierra" },
    { categoria: "Autos lujosos y de 4 puertas", tipo: "Tierra" },
    { categoria: "Camiones pesados y vehiculos utilitarios", tipo: "Tierra" },
    { categoria: "Camionetas ligeras y furgonetas", tipo: "Tierra" },
    { categoria: "Lowriders", tipo: "Tierra" },
    { categoria: "Motos", tipo: "Tierra" },
    { categoria: "Muscle cars", tipo: "Tierra" },
    { categoria: "Remolques", tipo: "Tierra" },
    { categoria: "SUVs y rurales", tipo: "Tierra" },
    { categoria: "Trenes y vagones", tipo: "Tierra" },
    { categoria: "Vehiculos de servicio civil", tipo: "Tierra" },
    { categoria: "Vehiculos gubernamentales", tipo: "Tierra" },
    { categoria: "Vehiculos RC", tipo: "Tierra" },
    { categoria: "Vehiculos recreativos", tipo: "Tierra" },
    { categoria: "Aviones", tipo: "Aire" },
    { categoria: "Helicopteros", tipo: "Aire" },
    { categoria: "Botes", tipo: "Mar" },
];

const arrayImagenes = [
    {
        nombre: "Tierra", data: [
            { "nombre": "alpha", "categoria": "Autos compactos y de 2 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "blistac", "categoria": "Autos compactos y de 2 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "bravura", "categoria": "Autos compactos y de 2 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "buccanee", "categoria": "Autos compactos y de 2 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "cadrona", "categoria": "Autos compactos y de 2 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "club", "categoria": "Autos compactos y de 2 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "esperant", "categoria": "Autos compactos y de 2 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "euros", "categoria": "Autos compactos y de 2 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "feltzer", "categoria": "Autos compactos y de 2 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "fortune", "categoria": "Autos compactos y de 2 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "hermes", "categoria": "Autos compactos y de 2 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "hustler", "categoria": "Autos compactos y de 2 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "majestic", "categoria": "Autos compactos y de 2 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "manana", "categoria": "Autos compactos y de 2 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "picador", "categoria": "Autos compactos y de 2 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "previon", "categoria": "Autos compactos y de 2 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "stallion", "categoria": "Autos compactos y de 2 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "tampa", "categoria": "Autos compactos y de 2 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "virgo", "categoria": "Autos compactos y de 2 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "banshee", "categoria": "Autos de carreras callejeras", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "bullet", "categoria": "Autos de carreras callejeras", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "cheetah", "categoria": "Autos de carreras callejeras", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "comet", "categoria": "Autos de carreras callejeras", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "elegy", "categoria": "Autos de carreras callejeras", "estado": "ambos", "textura": "nada", "material": "nada" },
            { "nombre": "flash", "categoria": "Autos de carreras callejeras", "estado": "ambos", "textura": "nada", "material": "nada" },
            { "nombre": "hotknife", "categoria": "Autos de carreras callejeras", "estado": "ambos", "textura": "nada", "material": "nada" },
            { "nombre": "hotrina", "categoria": "Autos de carreras callejeras", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "hotrinb", "categoria": "Autos de carreras callejeras", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "hotring", "categoria": "Autos de carreras callejeras", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "infernus", "categoria": "Autos de carreras callejeras", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "jester", "categoria": "Autos de carreras callejeras", "estado": "ambos", "textura": "nada", "material": "nada" },
            { "nombre": "stratum", "categoria": "Autos de carreras callejeras", "estado": "ambos", "textura": "nada", "material": "nada" },
            { "nombre": "sultan", "categoria": "Autos de carreras callejeras", "estado": "ambos", "textura": "nada", "material": "nada" },
            { "nombre": "supergt", "categoria": "Autos de carreras callejeras", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "turismo", "categoria": "Autos de carreras callejeras", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "uranus", "categoria": "Autos de carreras callejeras", "estado": "ambos", "textura": "nada", "material": "nada" },
            { "nombre": "windsor", "categoria": "Autos de carreras callejeras", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "zr350", "categoria": "Autos de carreras callejeras", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "admiralf", "categoria": "Autos lujosos y de 4 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "elegantf", "categoria": "Autos lujosos y de 4 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "emperorf", "categoria": "Autos lujosos y de 4 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "glendalef", "categoria": "Autos lujosos y de 4 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "glenshitf", "categoria": "Autos lujosos y de 4 puertas", "estado": "ok", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "greenwoof", "categoria": "Autos lujosos y de 4 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "intruderf", "categoria": "Autos lujosos y de 4 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "meritf", "categoria": "Autos lujosos y de 4 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "nebulaf", "categoria": "Autos lujosos y de 4 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "oceanicf", "categoria": "Autos lujosos y de 4 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "premierf", "categoria": "Autos lujosos y de 4 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "primof", "categoria": "Autos lujosos y de 4 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "sentinelf", "categoria": "Autos lujosos y de 4 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "staffordf", "categoria": "Autos lujosos y de 4 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "stretchf", "categoria": "Autos lujosos y de 4 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "sunrisef", "categoria": "Autos lujosos y de 4 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "tahomaf", "categoria": "Autos lujosos y de 4 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "vincentf", "categoria": "Autos lujosos y de 4 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "washingf", "categoria": "Autos lujosos y de 4 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "willardf", "categoria": "Autos lujosos y de 4 puertas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "benson", "categoria": "Camiones pesados y vehiculos utilitarios", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "boxburg", "categoria": "Camiones pesados y vehiculos utilitarios", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "boxville", "categoria": "Camiones pesados y vehiculos utilitarios", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "cement", "categoria": "Camiones pesados y vehiculos utilitarios", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary, third" },
            { "nombre": "combine", "categoria": "Camiones pesados y vehiculos utilitarios", "estado": "ok", "textura": "nada", "material": "nada" },
            { "nombre": "dft30", "categoria": "Camiones pesados y vehiculos utilitarios", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "dozer", "categoria": "Camiones pesados y vehiculos utilitarios", "estado": "nada", "textura": "vehiclegrunge256.PNG", "material": "misc_a" },
            { "nombre": "dumper", "categoria": "Camiones pesados y vehiculos utilitarios", "estado": "ok", "textura": "vehiclegrunge256.PNG", "material": "chassis, door_lf_ok" },
            { "nombre": "duneride", "categoria": "Camiones pesados y vehiculos utilitarios", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "flatbed", "categoria": "Camiones pesados y vehiculos utilitarios", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "hotdog", "categoria": "Camiones pesados y vehiculos utilitarios", "estado": "ambos", "textura": "nada", "material": "nada" },
            { "nombre": "linerun", "categoria": "Camiones pesados y vehiculos utilitarios", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "mrwhoop", "categoria": "Camiones pesados y vehiculos utilitarios", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "mule", "categoria": "Camiones pesados y vehiculos utilitarios", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "packer", "categoria": "Camiones pesados y vehiculos utilitarios", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "petro", "categoria": "Camiones pesados y vehiculos utilitarios", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "rdtrain", "categoria": "Camiones pesados y vehiculos utilitarios", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "tractor", "categoria": "Camiones pesados y vehiculos utilitarios", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "yankee", "categoria": "Camiones pesados y vehiculos utilitarios", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "bobcat", "categoria": "Camionetas ligeras y furgonetas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "burrito", "categoria": "Camionetas ligeras y furgonetas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "forklift", "categoria": "Camionetas ligeras y furgonetas", "estado": "nada", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "moonbeam", "categoria": "Camionetas ligeras y furgonetas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "mower", "categoria": "Camionetas ligeras y furgonetas", "estado": "ok", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "newsvan", "categoria": "Camionetas ligeras y furgonetas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "pony", "categoria": "Camionetas ligeras y furgonetas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "rumpo", "categoria": "Camionetas ligeras y furgonetas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "sadler", "categoria": "Camionetas ligeras y furgonetas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "boot_ok, primary" },
            { "nombre": "sadlshit", "categoria": "Camionetas ligeras y furgonetas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "boot_ok, primary" },
            { "nombre": "topfun", "categoria": "Camionetas ligeras y furgonetas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "tug", "categoria": "Camionetas ligeras y furgonetas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "walton", "categoria": "Camionetas ligeras y furgonetas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "yosemite", "categoria": "Camionetas ligeras y furgonetas", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "blade", "categoria": "Lowriders", "estado": "ambos", "textura": "nada", "material": "nada" },
            { "nombre": "broadway", "categoria": "Lowriders", "estado": "ambos", "textura": "nada", "material": "nada" },
            { "nombre": "remingtn", "categoria": "Lowriders", "estado": "ambos", "textura": "nada", "material": "nada" },
            { "nombre": "savanna", "categoria": "Lowriders", "estado": "ambos", "textura": "nada", "material": "nada" },
            { "nombre": "slamvan", "categoria": "Lowriders", "estado": "ambos", "textura": "nada", "material": "nada" },
            { "nombre": "tornado", "categoria": "Lowriders", "estado": "ambos", "textura": "nada", "material": "nada" },
            { "nombre": "voodoo", "categoria": "Lowriders", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "bf400", "categoria": "Motos", "estado": "nada", "textura": "nada", "material": "nada" },
            { "nombre": "bike", "categoria": "Motos", "estado": "nada", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "bmx", "categoria": "Motos", "estado": "nada", "textura": "nada", "material": "nada" },
            { "nombre": "faggio", "categoria": "Motos", "estado": "nada", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "fcr900", "categoria": "Motos", "estado": "nada", "textura": "nada", "material": "nada" },
            { "nombre": "freeway", "categoria": "Motos", "estado": "nada", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "mtbike", "categoria": "Motos", "estado": "nada", "textura": "nada", "material": "nada" },
            { "nombre": "nrg500", "categoria": "Motos", "estado": "nada", "textura": "nada", "material": "nada" },
            { "nombre": "pcj600", "categoria": "Motos", "estado": "nada", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "pizzaboy", "categoria": "Motos", "estado": "nada", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "sanchez", "categoria": "Motos", "estado": "nada", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "wayfarer", "categoria": "Motos", "estado": "nada", "textura": "nada", "material": "nada" },
            { "nombre": "buffalo", "categoria": "Muscle cars", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "clover", "categoria": "Muscle cars", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "phoenix", "categoria": "Muscle cars", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "sabre", "categoria": "Muscle cars", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "artict1", "categoria": "Remolques", "estado": "nada", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "artict2", "categoria": "Remolques", "estado": "nada", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "artict3", "categoria": "Remolques", "estado": "nada", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "bagboxa", "categoria": "Remolques", "estado": "nada", "textura": "nada", "material": "nada" },
            { "nombre": "bagboxb", "categoria": "Remolques", "estado": "nada", "textura": "nada", "material": "nada" },
            { "nombre": "farmtr1", "categoria": "Remolques", "estado": "nada", "textura": "nada", "material": "nada" },
            { "nombre": "petrotr", "categoria": "Remolques", "estado": "nada", "textura": "nada", "material": "nada" },
            { "nombre": "tugstair", "categoria": "Remolques", "estado": "nada", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "utiltr1", "categoria": "Remolques", "estado": "nada", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "huntley", "categoria": "SUVs y rurales", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "landstal", "categoria": "SUVs y rurales", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "peren", "categoria": "SUVs y rurales", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "rancher", "categoria": "SUVs y rurales", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "regina", "categoria": "SUVs y rurales", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "rnchlure", "categoria": "SUVs y rurales", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "romero", "categoria": "SUVs y rurales", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "solair", "categoria": "SUVs y rurales", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "freibox", "categoria": "Trenes y vagones", "estado": "ok", "textura": "nada", "material": "nada" },
            { "nombre": "freiflat", "categoria": "Trenes y vagones", "estado": "nada", "textura": "nada", "material": "nada" },
            { "nombre": "freight", "categoria": "Trenes y vagones", "estado": "ok", "textura": "nada", "material": "nada" },
            { "nombre": "streak", "categoria": "Trenes y vagones", "estado": "ok", "textura": "nada", "material": "nada" },
            { "nombre": "streakc", "categoria": "Trenes y vagones", "estado": "ok", "textura": "nada", "material": "nada" },
            { "nombre": "tram", "categoria": "Trenes y vagones", "estado": "ok", "textura": "nada", "material": "nada" },
            { "nombre": "baggage", "categoria": "Vehiculos de servicio civil", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "chassis" },
            { "nombre": "bus", "categoria": "Vehiculos de servicio civil", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "chassis, primary, secondary" },
            { "nombre": "cabbie", "categoria": "Vehiculos de servicio civil", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "coach", "categoria": "Vehiculos de servicio civil", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "door_lf_ok, primary, secondary" },
            { "nombre": "sweeper", "categoria": "Vehiculos de servicio civil", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "taxi", "categoria": "Vehiculos de servicio civil", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "towtruck", "categoria": "Vehiculos de servicio civil", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "door_lf_ok, primary, secondary" },
            { "nombre": "trash", "categoria": "Vehiculos de servicio civil", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "ambulan", "categoria": "Vehiculos gubernamentales", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "secondary" },
            { "nombre": "barracks", "categoria": "Vehiculos gubernamentales", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "door_lf_ok" },
            { "nombre": "copbike", "categoria": "Vehiculos gubernamentales", "estado": "nada", "textura": "nada", "material": "nada" },
            { "nombre": "copcarla", "categoria": "Vehiculos gubernamentales", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "copcarru", "categoria": "Vehiculos gubernamentales", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "copcarsf", "categoria": "Vehiculos gubernamentales", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "copcarvg", "categoria": "Vehiculos gubernamentales", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "enforcer", "categoria": "Vehiculos gubernamentales", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "fbiranch", "categoria": "Vehiculos gubernamentales", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "fbitruck", "categoria": "Vehiculos gubernamentales", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "bonnet_ok" },
            { "nombre": "firela", "categoria": "Vehiculos gubernamentales", "estado": "ok", "textura": "vehiclegrunge256.PNG", "material": "door_lf_ok, primary" },
            { "nombre": "firetruk", "categoria": "Vehiculos gubernamentales", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "door_lf_ok, primary" },
            { "nombre": "patriot", "categoria": "Vehiculos gubernamentales", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "bonnet_ok" },
            { "nombre": "rhino", "categoria": "Vehiculos gubernamentales", "estado": "ok", "textura": "nada", "material": "nada" },
            { "nombre": "securica", "categoria": "Vehiculos gubernamentales", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "swatvan", "categoria": "Vehiculos gubernamentales", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "door_lf_ok" },
            { "nombre": "rcbandit", "categoria": "Vehiculos RC", "estado": "nada", "textura": "nada", "material": "nada" },
            { "nombre": "rcbaron", "categoria": "Vehiculos RC", "estado": "ok", "textura": "nada", "material": "nada" },
            { "nombre": "rcgoblin", "categoria": "Vehiculos RC", "estado": "nada", "textura": "nada", "material": "nada" },
            { "nombre": "rcraider", "categoria": "Vehiculos RC", "estado": "nada", "textura": "nada", "material": "nada" },
            { "nombre": "rctiger", "categoria": "Vehiculos RC", "estado": "nada", "textura": "nada", "material": "nada" },
            { "nombre": "bandito", "categoria": "Vehiculos recreativos", "estado": "ambos", "textura": "nada", "material": "nada" },
            { "nombre": "bfinject", "categoria": "Vehiculos recreativos", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "bloodra", "categoria": "Vehiculos recreativos", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "caddy", "categoria": "Vehiculos recreativos", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "camper", "categoria": "Vehiculos recreativos", "estado": "ambos", "textura": "nada", "material": "nada" },
            { "nombre": "journey", "categoria": "Vehiculos recreativos", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "kart", "categoria": "Vehiculos recreativos", "estado": "ambos", "textura": "nada", "material": "nada" },
            { "nombre": "mesa", "categoria": "Vehiculos recreativos", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "monster", "categoria": "Vehiculos recreativos", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "monstera", "categoria": "Vehiculos recreativos", "estado": "ok", "textura": "nada", "material": "nada" },
            { "nombre": "monsterb", "categoria": "Vehiculos recreativos", "estado": "ok", "textura": "nada", "material": "nada" },
            { "nombre": "quad", "categoria": "Vehiculos recreativos", "estado": "nada", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "sandking", "categoria": "Vehiculos recreativos", "estado": "ambos", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "vortex", "categoria": "Vehiculos recreativos", "estado": "nada", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
        ],
    },
    {
        nombre: "Aire", data: [
            { "nombre": "androm", "categoria": "Aviones", "estado": "ok", "textura": "nada", "material": "nada" },
            { "nombre": "at400", "categoria": "Aviones", "estado": "ok", "textura": "nada", "material": "nada" },
            { "nombre": "beagle", "categoria": "Aviones", "estado": "ok", "textura": "nada", "material": "nada" },
            { "nombre": "cropdust", "categoria": "Aviones", "estado": "ok", "textura": "nada", "material": "nada" },
            { "nombre": "dodo", "categoria": "Aviones", "estado": "ok", "textura": "nada", "material": "nada" },
            { "nombre": "hydra", "categoria": "Aviones", "estado": "ok", "textura": "nada", "material": "nada" },
            { "nombre": "nevada", "categoria": "Aviones", "estado": "ok", "textura": "nada", "material": "nada" },
            { "nombre": "rustler", "categoria": "Aviones", "estado": "ok", "textura": "nada", "material": "nada" },
            { "nombre": "shamal", "categoria": "Aviones", "estado": "ok", "textura": "nada", "material": "nada" },
            { "nombre": "skimmer", "categoria": "Aviones", "estado": "ok", "textura": "vehiclegrunge256.PNG", "material": "secondary" },
            { "nombre": "stunt", "categoria": "Aviones", "estado": "ok", "textura": "nada", "material": "nada" },
            { "nombre": "cargobob", "categoria": "Helicopteros", "estado": "ok", "textura": "nada", "material": "nada" },
            { "nombre": "hunter", "categoria": "Helicopteros", "estado": "ok", "textura": "nada", "material": "nada" },
            { "nombre": "leviathn", "categoria": "Helicopteros", "estado": "ok", "textura": "nada", "material": "nada" },
            { "nombre": "maverick", "categoria": "Helicopteros", "estado": "ok", "textura": "nada", "material": "nada" },
            { "nombre": "polmav", "categoria": "Helicopteros", "estado": "ok", "textura": "nada", "material": "nada" },
            { "nombre": "raindanc", "categoria": "Helicopteros", "estado": "ok", "textura": "nada", "material": "nada" },
            { "nombre": "seaspar", "categoria": "Helicopteros", "estado": "ok", "textura": "nada", "material": "nada" },
            { "nombre": "sparrow", "categoria": "Helicopteros", "estado": "ok", "textura": "nada", "material": "nada" },
            { "nombre": "vcnmav", "categoria": "Helicopteros", "estado": "ok", "textura": "nada", "material": "nada" },
        ],
    },
    {
        nombre: "Mar", data: [
            { "nombre": "coastg", "categoria": "Botes", "estado": "nada", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "dinghy", "categoria": "Botes", "estado": "nada", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "jetmax", "categoria": "Botes", "estado": "nada", "textura": "nada", "material": "nada" },
            { "nombre": "launch", "categoria": "Botes", "estado": "nada", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "marquis", "categoria": "Botes", "estado": "nada", "textura": "nada", "material": "nada" },
            { "nombre": "predator", "categoria": "Botes", "estado": "nada", "textura": "vehiclegrunge256.PNG", "material": "primary" },
            { "nombre": "reefer", "categoria": "Botes", "estado": "nada", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "speeder", "categoria": "Botes", "estado": "nada", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary" },
            { "nombre": "squalo", "categoria": "Botes", "estado": "nada", "textura": "vehiclegrunge256.PNG", "material": "primary, secondary, third" },
            { "nombre": "tropic", "categoria": "Botes", "estado": "nada", "textura": "vehiclegrunge256.PNG", "material": "primary" },
        ],
    }
];

const arrayTexturas = [
    {
        nombre: "vehiclegrunge256.PNG", data: [
            { textura: "grunge01" },
            { textura: "grunge02" },
            { textura: "grunge03" },
            { textura: "grunge04" },
            { textura: "grunge05" },
            { textura: "grunge06" },
            { textura: "grunge07" },
            { textura: "grunge08" },
            { textura: "grunge09" },
            { textura: "grunge10" },
            { textura: "grunge11" },
            { textura: "grunge12" },
            { textura: "grunge13" },
            { textura: "grunge14" },
            { textura: "grunge15" },
            { textura: "grunge16" },
            { textura: "grunge17" },
            { textura: "grunge18" },
            { textura: "grunge19" },
            { textura: "grunge20" },
            { textura: "grunge21" },
            { textura: "grunge22" },
            { textura: "grunge23" },
            { textura: "grunge24" },
            { textura: "grunge25" },
            { textura: "grunge26" },
            { textura: "grunge27" },
            { textura: "grunge28" },
            { textura: "grunge29" },
            { textura: "grunge30" },
            { textura: "grunge31" },
            { textura: "grunge32" },
            { textura: "grunge33" },
            { textura: "grunge34" },
            { textura: "grunge35" },
            { textura: "grunge36" },
            { textura: "grunge37" },
            { textura: "grunge38" },
            { textura: "grunge39" },
            { textura: "grunge40" },
            { textura: "grunge41" },
            { textura: "grunge42" },
            { textura: "grunge43" },
            { textura: "grunge44" },
            { textura: "grunge45" },
            { textura: "grunge46" },
            { textura: "grunge47" },
            { textura: "grunge48" },
            { textura: "grunge49" },
            { textura: "grunge50" },
            { textura: "grunge51" },
            { textura: "grunge52" },
            { textura: "grunge53" },
            { textura: "grunge54" },
            { textura: "grunge55" },
            { textura: "grunge56" },
            { textura: "grunge57" },
            { textura: "grunge58" },
            { textura: "grunge59" },
            { textura: "grunge60" },
            { textura: "grunge61" },
            { textura: "grunge62" },
            { textura: "grunge63" },
            { textura: "grunge64" },
            { textura: "grunge65" },
            { textura: "grunge66" },
            { textura: "grunge67" },
            { textura: "grunge68" },
            { textura: "grunge69" },
            { textura: "grunge70" },
            { textura: "grunge71" },
            { textura: "grunge72" },
            { textura: "grunge73" },

        ]
    },
    {
        nombre: "ground001.png", data: [
            { textura: "001" },
            { textura: "002" },
            { textura: "003" },
            { textura: "004" },
        ]
    }
];
